### ISSUE TITLE
raynebc/Berneer/cstewart chord slide with tech notes bug

### ISSUE THREAD

**Issue by Berneer** [rscustom/rocksmith-custom-song-toolkit#153]
Hello devs,

raynebc has been working hard to resolve an issue in the last two Hotfixes now which unfortunately do not resolve a problem and he thinks that all avenues of solution have been exhausted and it is time to open a bug report. I have been helping out testing his solutions so I am writing the bug report.

Briefly, raynebc introduced EoF logic that seems to export perfectly in XML that uses Tech notes to use linknext and  stop tech notes to split up chords into spearate notes each doing their independant thing. 

If you look at the screenshot below you will notice that there are 2 issues:

1)There should be 3 total yellow open A string notes (without sustains due to the use of new  STOP tech notes new to Hotfix 1300), but only 1 shows up. I've circled yellow exclamation points that do show up in-game where the open notes should be. Problem is that those yellow exclamation points should be accompanied with yellow open A-string notes.

2) With linknext status tech notes (now fully functional in Hotfix 1300) on all but the last sustain notes on the orange G-string, we'd expect to have one note head at the beginning and one at the end as per the screenshot, yet I've circled one appearing near the middle of the long sustain. It is difficult to tell from the screenshot but the note head appearing corresponds to the last of the 6th fret notes on the orange G string.

raynebc and I believe this is a type of authorin is not uncommon and will have widespread appeal and is worthy of the effort to get it working right so we are hoping you can resolve this bug.

Here is the corresponding XML output exported by EoF that both raynebc and I get identical to one another and which seems logical:

        <note time="102.315" linkNext="1" accent="0" bend="0" fret="4" hammerOn="0" harmonic="0" hopo="0" ignore="0" leftHand="-1" mute="0" palmMute="0" pluck="-1" pullOff="0" slap="-1" slideTo="6" string="3" sustain="0.250" tremolo="0" harmonicPinch="0" pickDirection="0" rightHand="-1" slideUnpitchTo="-1" tap="0" vibrato="0"/>
        <note time="102.565" linkNext="0" accent="0" bend="0" fret="0" hammerOn="0" harmonic="0" hopo="0" ignore="0" leftHand="-1" mute="0" palmMute="0" pluck="-1" pullOff="0" slap="-1" slideTo="-1" string="1" sustain="0.000" tremolo="0" harmonicPinch="0" pickDirection="0" rightHand="-1" slideUnpitchTo="-1" tap="0" vibrato="0"/>
        <note time="102.565" linkNext="1" accent="0" bend="0" fret="6" hammerOn="0" harmonic="0" hopo="0" ignore="0" leftHand="-1" mute="0" palmMute="0" pluck="-1" pullOff="0" slap="-1" slideTo="-1" string="3" sustain="0.500" tremolo="0" harmonicPinch="0" pickDirection="0" rightHand="-1" slideUnpitchTo="-1" tap="0" vibrato="0"/>
        <note time="103.065" linkNext="0" accent="0" bend="0" fret="0" hammerOn="0" harmonic="0" hopo="0" ignore="0" leftHand="-1" mute="0" palmMute="0" pluck="-1" pullOff="0" slap="-1" slideTo="-1" string="1" sustain="0.000" tremolo="0" harmonicPinch="0" pickDirection="0" rightHand="-1" slideUnpitchTo="-1" tap="0" vibrato="0"/>
        <note time="103.065" linkNext="1" accent="0" bend="0" fret="6" hammerOn="0" harmonic="0" hopo="0" ignore="0" leftHand="-1" mute="0" palmMute="0" pluck="-1" pullOff="0" slap="-1" slideTo="-1" string="3" sustain="0.250" tremolo="0" harmonicPinch="0" pickDirection="0" rightHand="-1" slideUnpitchTo="-1" tap="0" vibrato="0"/>
        <note time="103.315" linkNext="1" accent="0" bend="0" fret="6" hammerOn="0" harmonic="0" hopo="0" ignore="0" leftHand="-1" mute="0" palmMute="0" pluck="-1" pullOff="0" slap="-1" slideTo="4" string="3" sustain="0.250" tremolo="0" harmonicPinch="0" pickDirection="0" rightHand="-1" slideUnpitchTo="-1" tap="0" vibrato="0"/>
        <note time="103.565" linkNext="0" accent="0" bend="0" fret="0" hammerOn="0" harmonic="0" hopo="0" ignore="0" leftHand="-1" mute="0" palmMute="0" pluck="-1" pullOff="0" slap="-1" slideTo="-1" string="1" sustain="0.000" tremolo="0" harmonicPinch="0" pickDirection="0" rightHand="-1" slideUnpitchTo="-1" tap="0" vibrato="0"/>
        <note time="103.565" linkNext="0" accent="0" bend="0" fret="4" hammerOn="0" harmonic="0" hopo="0" ignore="0" leftHand="-1" mute="0" palmMute="0" pluck="-1" pullOff="0" slap="-1" slideTo="-1" string="3" sustain="0.247" tremolo="0" harmonicPinch="0" pickDirection="0" rightHand="-1" slideUnpitchTo="-1" tap="0" vibrato="0"/>
        <note time="103.815" linkNext="0" accent="0" bend="0" fret="4" hammerOn="0" harmonic="0" hopo="0" ignore="0" leftHand="-1" mute="0" palmMute="0" pluck="-1" pullOff="0" slap="-1" slideTo="-1" string="3" sustain="0.000" tremolo="0" harmonicPinch="0" pickDirection="0" rightHand="-1" slideUnpitchTo="-1" tap="0" vibrato="0"/>

![bug report - raynebc slide needs help from toolkit developpers](https://f.cloud.github.com/assets/6868809/2345650/5d80f6fe-a538-11e3-8ec4-981f357d30ac.png)

Thank-you for your attention and for all your amazing work!

**Comment by L0FKA** [comment]
resolved at eof side
