### ISSUE TITLE
Encoding WEM

### ISSUE THREAD

**Issue by otaznik** [rscustom/rocksmith-custom-song-toolkit#17]
This is something to be desired in the future.  It can be external tool distributed separately which uses Wwise library, if that's possible.

**Comment by cozy1** [comment]
I know this is different issue, but can we close this since we added Wwise auto convert script to toolkit?

**Comment by L0FKA** [comment]
I'd like to have another tool vvhich just adapts ogg file to vvem file,vvhich isn't so hard to reach, that should reduce CDLC generation times, but this goal looks like reached vvith vvvviseCLI, vvhich uses it's ovvn library :D

Closed.
