### ISSUE TITLE
PSARC class can exceed open files limit on Mac

### ISSUE THREAD

**Issue by fholger** [rscustom/rocksmith-custom-song-toolkit#188]
For my RocksmithToTab converter, I've been using the PSARC class to read in .psarc archives and extract the song arrangements from them. However, when I tried to get my program to work on the Mac, I ran into a problem when trying to open the songs.psarc file. The program would fail with the message "too many open files".

What's happening is the following: The PSARC class opens the psarc in memory, and then for every file there is in the archive, it creates a temporary file, extracts the file contents to it, and keeps the file stream open for future access. Now, since the larger archives like songs.psarc, and possibly also the rs1compatibility*.psarc, contain >2000 files, we are exceeding the file handle limit for a single process on Unix platforms, which is typically 1024 or so. As a first try, I changed the TempFileStreams to MemoryStreams, but then the program runs out of memory, instead.

To fix this, the class needs to be changed to not extract all of the files in the archives right away, but only do it on demand. This also drastically reduces the load time for such an archive if you don't actually need to access all the files. For my converter, I've created a local copy of the class where I changed the behaviour to do just that. If you'd like, you can check it out there: https://github.com/fholger/RocksmithToTab/blob/master/RocksmithToTabLib/PSARC.cs

However, my workaround only supports reading psarcs, whereas the original also has write support. I'm not entirely sure what would be the best way to defer opening the files until the actual write happens, so I left that out, since I don't need it. Either way, fixing this will certainly break the interface of the class. 

I don't know how much this class is used, anyway. Maybe it's not a big deal. I just wanted to report the problem for now. In any event, this is not a problem for the "typical" toolkit use, since most users probably wouldn't need to access such big psarc archives, anyway. So my use case is a little out of the ordinary :)

**Comment by L0FKA** [comment]
@fholger, I need someone to confirm that unpacker works for OS X with large psarc's like 'etudes'

For now I assume it's fixed and close the issue.(Not that I don't like Idea about lazy acces to files from psarc, We just don;t really work that way for now)
