### ISSUE TITLE
Rocksmith2014 Official DLC fails to convert to PS3

### ISSUE THREAD

**Issue by catara** [rscustom/rocksmith-custom-song-toolkit#190]
Original DLC does not convert from PC(or mac) to PS3:

Iron Maiden - Aces High aceshigh_p.psarc
B'z - Giri Giri chop girigirichop_p.psarc
Hotei - Bambino hoteibambino_p.psarc
Muse - Time Is Running Out musetime_p.psarc
Oasis - Supersonic oasissuper_p.psarc

Source files from
http://www.rocksmith.tk/Rocksmith2014/
or in case links are down(e.g. hotei)  or for to access the Error log: http://goo.gl/gC2qKy

**Comment by TheDeadStone** [comment]
> old DLCs conv fixed ....(1more xml issue on a shinesecond_p DLC; to open later as no log saved)

It is not fixed in last release

**Comment by L0FKA** [comment]
Read lines above, it's not officially supported to convert non cdlc to any other platforms.
