### ISSUE TITLE
version number field upgrade

### ISSUE THREAD

**Issue by MadMaxxx** [rscustom/rocksmith-custom-song-toolkit#192]
enhancement request

what do you  think about the idea to change the version number field to one where like the two volume fields where you can use the up and down arrow to increment by 0.1

 manual input should still be allowed like the volume fields for those who like to a number like 1.23

**Comment by cozy1** [comment]
This is string field so just create each decimal digit(s) as separate field.  Like odometer where you change each number separately  like this:  String.Format({0}.{1}.{2}, revMajor, revMinor, revBuild)  Let me know if you want me to put this on my TODO: list.

**Comment by L0FKA** [comment]
I think I have some good Idea 'bout this I'll play vvith this in this month.

**Comment by colejohnson66** [comment]
Just FYI: Standard programming practice is: if you're not gonna do math with it, it's not a number. Version numbers are a _collection_ of numbers separated by (typically) a dot (period). It shouldn't be stored as a `float`, but as a `string`.

**Comment by cozy1** [comment]
Very old issue.  Version field has been revised multiple times and no new user comments.  So closing this issue.
