### ISSUE TITLE
false positive in anti virus?

### ISSUE THREAD

**Issue by silencer666** [rscustom/rocksmith-custom-song-toolkit#197]
A number of major anti-virus programmes believes that this file contains malware. Source: http://bit.ly/1FHOnQ9

**Comment by cozy1** [comment]
Does this address the issue and can it be closed?  https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/fe59ccde5519f40c32aec537d17aec4e49510e85

**Comment by cozy1** [comment]
Dev responded and there was no further followup from originator.
