### ISSUE TITLE
Rocksmith Custom Song Creator Toolkit has stopped working?

### ISSUE THREAD

**Issue by AJSLOANE** [rscustom/rocksmith-custom-song-toolkit#199]
I can never launch the application and it always says "Rocksmith Custom Song Creator Toolkit has stopped working" Im using Windows Vista and im wondering if i can fix this.

**Comment by ray** [comment]
Make sure you have the latest .NET framework, http://go.microsoft.com/?linkid=9831986
Vista comes with an older version.

**Comment by L0FKA** [comment]
Works great with old net and new net tho
