### ISSUE TITLE
[xbox360] packer cache.psarc error

### ISSUE THREAD

**Issue by 52mzd** [rscustom/rocksmith-custom-song-toolkit#200]
unpacker cache.psarc,then paper to cache.psarc
can't run on xbox360

**Comment by catara** [comment]
same on PS3
(10kb diff after packing)

**Comment by catara** [comment]
looks like the cache.psarc should contain only non compressed files inside(as it already has only 7z archives)

....use Total Commander with the psarc pluginhttp://www.totalcmd.net/plugring/PSARC.html configured to no 0 compression ratio and rocksmith will boot

... just did a test to take out all the retails shipped songs by modifying songs.hsan...and then repacked cache.psarc using Total Commander http://www.totalcmd.net/ ...to have it working on PS3

**Comment by L0FKA** [comment]
Our aim is songs for now, but you could use (packer.exe)CLI tool for this and you'll be fine, I'm closing this
