### ISSUE TITLE
Error generate PC package

### ISSUE THREAD

**Issue by gustavixp** [rscustom/rocksmith-custom-song-toolkit#203]
When I generate it I get an error saying 'Error generate PC package: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection'

![image](https://cloud.githubusercontent.com/assets/11137813/6315254/d8f29034-b9e3-11e4-8b36-1fc055a5c520.png)

**Comment by L0FKA** [comment]
please use latest build and if it won't work? then post files so I could investigate yours problem:)

**Comment by gustavixp** [comment]
Thank you, you have no idea how much helped me :D
