### ISSUE TITLE
Manifest not updated when using "packer.exe" to pack a CDLC

### ISSUE THREAD

**Issue by Chlipouni** [rscustom/rocksmith-custom-song-toolkit#205]
Is it possible to add an option to update the manifest when packing a CDLC with the packer command line tool ?

**Comment by L0FKA** [comment]
Sorry long dela in this I  couldn't work on this, so anone who acn implement it please do *O*

**Comment by Chlipouni** [comment]
What I need is to apply the following code (from "DDC.cs") into "packer/Program.cs" 
    // UPDATE MANIFEST (RS2014) for update
                if (platform.version == RocksmithToolkitLib.GameVersion.RS2014) {
                    var json = Directory.GetFiles(unpackedDir, String.Format("*{0}.json", Path.GetFileNameWithoutExtension(xml)), SearchOption.AllDirectories);
                    if (json.Length > 0) {
                        Attributes2014 attr = Manifest2014<Attributes2014>.LoadFromFile(json[0]).Entries.ToArray()[0].Value.ToArray()[0].Value;
                        Song2014 xmlContent = Song2014.LoadFromFile(xml);

                        var manifestFunctions = new ManifestFunctions(platform.version);

                        attr.PhraseIterations = new List<PhraseIteration>();
                        manifestFunctions.GeneratePhraseIterationsData(attr, xmlContent, platform.version);

                        attr.Phrases = new List<Phrase>();
                        manifestFunctions.GeneratePhraseData(attr, xmlContent);

                        attr.Sections = new List<Section>();
                        manifestFunctions.GenerateSectionData(attr, xmlContent);

                        attr.MaxPhraseDifficulty = manifestFunctions.GetMaxDifficulty(xmlContent);

                        var manifest = new Manifest2014<Attributes2014>();
                        var attributeDictionary = new Dictionary<string, Attributes2014> { { "Attributes", attr } };
                        manifest.Entries.Add(attr.PersistentID, attributeDictionary);
                        manifest.SaveToFile(json[0]);
                    }
                }

Thanks

**Comment by L0FKA** [comment]
So you implemented it already :D
Yo could just pull request it here, but I'll merge it now, thank you, @Chlipouni !

**Comment by Chlipouni** [comment]
I think that its your own code ;-) that you have made for a previous
request ...
But this request was only for the DDC tab when using "psarc" files.

I now need it for the "packer.exe" program, as I could use it directly with
BPR ;-)

Thank you a lot

2015-02-28 16:12 GMT+01:00 L0FKA <notifications@github.com>:

**Comment by L0FKA** [comment]
@Chlipouni implemented in feature branch, we'll finish with another one and I'll push it to master
