### ISSUE TITLE
Importing tones broke

### ISSUE THREAD

**Issue by Unleashed2k** [rscustom/rocksmith-custom-song-toolkit#206]
I'm not able to import tones since the latest beta update. 
It only shows .dat, xbox ".", and .json.

If I try to import the tone, there is nothing there.

**Comment by Unleashed2k** [comment]
Actually all tones are broke.

**Comment by L0FKA** [comment]
@Unleashed2k. we don't change any behavior in last commit in master branch, "import tone" is for Packages\json\profiles(select Xbox *.* to import it, NET can't filter OFD list with end prefix)
You can load tones from Tone2014.xml through tone edit window, edit default or add new one and load required tone :)

**Comment by Unleashed2k** [comment]
http://i.imgur.com/yXKbIGQ.png

psarc isn't showing anymore :)

**Comment by Unleashed2k** [comment]
The problem is when I load my toolkit file, it defaults all packages to convert. When I switch it back to Rocksmith 2014, it removes all tones. Something isn't right.

**Comment by Unleashed2k** [comment]
http://i.imgur.com/2FOB1wy.png when importing a tone

**Comment by L0FKA** [comment]
You're using wrong branch, I need to figure out how to prevent appveyor from building test branches :(

**Comment by L0FKA** [comment]
@Unleashed2k ^

**Comment by L0FKA** [comment]
Fixed in las commit, I suppouse ;)
