### ISSUE TITLE
Wwise CLI Integration - Expansion

### ISSUE THREAD

**Issue by cozy1** [rscustom/rocksmith-custom-song-toolkit#213]
Expand Wwise CLI integration to handle newer versions of Audiokinct Wwise.  Currently CST is only known to support Wwise v2013.2.2 build 4828.

**Comment by L0FKA** [comment]
This version is out of stock :)

**Comment by Firekorn** [comment]
I had it working with 2013.2.8 build 4865 that is still available on the wwise download page. Might worth that other try with different version too to know which one work or not
I wasn't able to try the 2.7 (error during install) and i haven't yet tested with 2.9 or 2.10.

**Comment by cozy1** [comment]
Any Wwise 48xx build works with current solution.  Closing this for now.
