### ISSUE TITLE
Can't convert original rs1compatibilitydlc_p to xbox 360 or ps3

### ISSUE THREAD

**Issue by N-Q-M** [rscustom/rocksmith-custom-song-toolkit#214]
I am trying to convert my legaly purchaged rs1compatibilitydisc_p to xbox but I get:

"Undefined tone name: importedtone_5"

Trying the conversion to ps3 I get the same error.

About piracy: I understand that rscustoms is not about cracking the original game files, but this is not a downloaded file from a P2P or something. I paid for it (the first time with the rocksmith purchage and the second one with the import tool purchage).

**Comment by fabianosan** [comment]
This project doesn't support conversion of oficial dlc. You need to support
the developer team and buy the dlc to play it.

**Comment by N-Q-M** [comment]
OK, my fault.

But about supporting the developer team, I have supported them with the RS1 (PC), with RS2014), with the compatibility disk (pc) and RS2014 xbox 360. I think i have contributed enought to them about the RS1 content. But sorry for asking rscustoms about that, i undertand your point of view.

Thanks.

**Comment by fabianosan** [comment]
Thanks for understanding man, sorry, but unfortunatelly we can't help you. In this case you need to buy the dlc for xbox or ps3 too.
