### ISSUE TITLE
XML file updated with error when adding a new arrangement in the creator tab.

### ISSUE THREAD

**Issue by Chlipouni** [rscustom/rocksmith-custom-song-toolkit#215]
In the last build, the XML file is updated with extra data after the "song" end tag (when generating with the creator tab).
So result XML file is not valid and DDC generates an error about it.

XML comments generated by EOF and DDC are losts, too.

Is it the expected behaviour that RSToolkit updates the submitted XML files ?

**Comment by cozy1** [comment]
The latest version of the toolkit does update the XML file(s) if the user make any changes to song information, e.g. title, date, tuning, tones, etc.  This is the expected behavior and gives greater flexibility to the user to make last minute changes or revisions to existing CDLC songs from within the toolkit.  I am not seeing the data you referenced after the "song" end tag in the latest version.

**Comment by Chlipouni** [comment]
Hi @cozy1,
  The issue seems to be solved with the last build "508acfcd83" as the XML file is no more updated when creating a new psarc file. Even in update mode, there is no more modification in the XML file.

  To reproduce the issue : 
  - Use the "a9d2fe5bb7" build
  - Use the "creator" tab and fill all fields (just one XML track; Lead for example)
  - Click on the "Generate" button
  - The XML file is updated and it contains 2 "/song" end tags.

In this case, the XML file is not valid and you can't open it with your browser.

Nothing against improvements in RSToolkit, I am just trying to help a few contributors that encountered this issue ...

**Comment by cozy1** [comment]
Yep.  Lofka changed my code to allow for user revisions to XML.  I am seeing the data you referenced after the "song" end tag in the latest version.  Only seems to occur with XML from EOF.  Not sure if I need to fix now that XML can not be revised.

**Comment by L0FKA** [comment]
Yes, I count on this issue and disabled updateXML feature, I think it could be re enabled after some fixes, for this.

**Comment by cozy1** [comment]
Fixed problem with Song end tag and re enabled update XML feature for further testing.

**Comment by cozy1** [comment]
Toolkit retains XML comments from DDC and EOF.
