### ISSUE TITLE
Getting errors upon generating

### ISSUE THREAD

**Issue by Unforgiven666** [rscustom/rocksmith-custom-song-toolkit#216]
Hi guys, 

Been trying to generate a p.psarc and always stumble upon an error:

 ![capture](https://cloud.githubusercontent.com/assets/6640568/6868843/3f9c1328-d465-11e4-8d65-433742cc6ec8.PNG)

I tried to update with the auto function but then, the package wasn't loadable. Some error about package being too new. 
I also tried re-filling the fields but that didn't help

Now, I saw the tones now have a base + 4 tones, Tone A use to be the default, do I still have to "duplicate" the tone from base to "A"? Like Distortion is my default tone, do I put it also in tone A?

Oh, and btw, I love the new tone import pop-up!

**Comment by L0FKA** [comment]
Yeah, I like it too, but it still buggy(no actual abort), I grabbed it from dlc to tab side ;)

As last commit says, it's not worth to update to new build, because it's highly bugged now, anyway, thx for reporting back, we'll handle this..

**Comment by Unforgiven666** [comment]
So, which build should I use in the meanwhile?

**Comment by Unleashed2k** [comment]
Yup very buggy as now when you add arrangements tones are messed up too for the last 24-48 hours.

**Comment by Unleashed2k** [comment]
All users are getting this update, so is it possible that you can create an alpha branch so all users do not get the buggy updates?

**Comment by zerkz** [comment]
@Unleashed2k  you could always pull down a "tag" instead of a branch.

**Comment by Unleashed2k** [comment]
@zerkz I'm using the official main toolkit build with the "beta" option enabled. Not really an option

**Comment by Unforgiven666** [comment]
Any idea which is the last stable built that I could use to go around this issue?

Also, I just saw the location C: projects.... doesn't exist. My toolkit is on G:

**Comment by L0FKA** [comment]
@Unforgiven666 i think it's appveyor build location at their server, it used just to inform you what file freaked out. I think this build is ok to use, it's pretty "outdated" but it much stable.
https://ci.appveyor.com/project/rscustom/rocksmith-custom-song-toolkit/build/7

**Comment by Firekorn** [comment]
I think the best question is why the non-beta branch is so outdated and doesn't contain all the "known to work" function of the beta release.

I think many charter activate the beta update because of that and many update without thinking that the update could break the basic function that were working before.

**Comment by L0FKA** [comment]
@fabianosan, could put that as stable, because it was stable enough, I know :(

We need to switch off main branch and go more deeply to git-flow type of releases, haha :(

**Comment by Unforgiven666** [comment]
Tried that older build to no avail...

Here's the log file

2015-03-27 23:15:04.1540 | RocksmithToolkitGUI.Program (INFO) : 
 RocksmithToolkitGUI.Program.Main 
 Version: 2.6.1.0-0dc4d7ad
 OS: Microsoft Windows NT 6.1.7601 Service Pack 1
 Command: "G:\Rocksmith Creator\Toolkit\RocksmithToolkitGUI.exe"

Tried again to rebuild from scratch. No avail
Kinda at a lost here

**Comment by Unforgiven666** [comment]
Ok, went back to EoF and redid the whole tone change.
Then, the package got generated.
Sounds like something from the EoF xmls
Probably a typo or something like that
My bad

Thanks for the help guys
