### ISSUE TITLE
Tones behaviour regression.

### ISSUE THREAD

**Issue by L0FKA** [rscustom/rocksmith-custom-song-toolkit#217]
Here: http://customsforge.com/topic/18113-undefined-tone-name/

**Comment by cozy1** [comment]
I found section of code that could generate this error.  I can fix when user posts link to EOF xml file to make sure I have the right area of code.

**Comment by cozy1** [comment]
Fixed tone not found error.  https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/ca31b7ec148119a649c906708629d3cf8ec45b73
