### ISSUE TITLE
Tuning Editor issues

### ISSUE THREAD

**Issue by MadMaxxx** [rscustom/rocksmith-custom-song-toolkit#218]
im running the latest revision 838c30c3cb

I have an issue with the Tuning Editior. I finished a project with a B Standard Tuning. I add the arr in the toolkit and the Tuning Editor window opens, i enter as a name B Standard, i also select "add as new Tuning" because the tuning is not in the list. Now i add the next arr and now the Tuning Editor windows pops up again. If i enter as a name again B Standard that tuning shows up twice in the Tuning selector, this should i think be prevented to have the same item twice in the tuning selector. At least a check should be added that checks if the names and the strings are the same.

A check should also be added when an arr is loaded to look first in the tuning list before showing the Tuning Editor window. I have in my tuning selector now B Standard twice and the Tuning Editor window shows up again.

**Comment by L0FKA** [comment]
It's not tunings editor issue it's more about adding\selecting nevv tunings from tuning repo, I think I'll vvor on tunings once again :)

**Comment by cozy1** [comment]
Resolved here http://customsforge.com/topic/989-custom-song-toolkit-v2600-was-released/page-12#entry142720
