### ISSUE TITLE
Tuning Editor issue #2 Strings Offset

### ISSUE THREAD

**Issue by MadMaxxx** [rscustom/rocksmith-custom-song-toolkit#219]
The tuning Editor does have an annoying bug where the strings get changed.

For example:
I added in my new project as first the guitar lead arr. The Tuning is B Standard, the Tuning Editor Pops up with all strings set to -5, i enter as a name B Standard and its in the tuning list.

Now i add the second Rhythm guitar arr and the Tuning Editor pops up again, now i select the X to close the Tuning Editor because the tuning is already in the tuning list. To double check it i click on ... and open up the tuning of that last added Rhythm guitar arr and i see that the strings are fucked up.

String 0 = -5
String 1 = -5
String 2 = -5
String 3 = -5
String 4 = 0
String 5 = 0

The last 2 Strings are set at 0 and thats wrong they should also be -5

**Comment by cozy1** [comment]
Resolved here http://customsforge.com/topic/989-custom-song-toolkit-v2600-was-released/page-12#entry142720
