### ISSUE TITLE
RSInjector for Mac - No more background images/animations

### ISSUE THREAD

**Issue by noreye** [rscustom/rocksmith-custom-song-toolkit#221]
Hi,

I am using the RSInjector for Mac and for some reason the background images/animations are gone. I just have a black background. I do see the 'sound' animations coming from the speakers on the side but no speakers.

Otherwise, everything else seems to works fine.
EDIT: actually, all the lessons are not showing up. the audio is there, just not the visual :(

Is anyone else seeing this?

Mac osx 10.9.5
RS 2014
Bass guitar

![screen shot 2015-05-01 at 18 57 37](https://cloud.githubusercontent.com/assets/5073080/7433687/2283598c-f034-11e4-9b1b-cf83343af3e9.png)

**Comment by L0FKA** [comment]
Have you enough free RAM?  again which version you've got? hope it's recent one, not just installed from disk, there was couple updates from it's first release, also there is available rsinjector bug tracker(https://github.com/rscustom/RSInjector-Mac/issues), It's not toolkit related issue to be clear :)

**Comment by noreye** [comment]
Ok, so I deleted the steam folder and app. did a clean reinstall of steam, added CDLC and everyting works fine.
I didnt even have to run the RSInjector :)

I have 16gb ram in my system so its ok :)

**Comment by L0FKA** [comment]
you may damage smth in previous install, but I'm glad you sorted this out
