### ISSUE TITLE
Missing Song's IDs

### ISSUE THREAD

**Issue by wewlad** [rscustom/rocksmith-custom-song-toolkit#222]
Guys, some song's IDs are missing. I bought Through the Glass by Stone Sour DLC, however i cannot find it's ID anywhere so I cannot get any Custom DLC. Please help

**Comment by ray** [comment]
We generally don't update the list because there's no demand for it, all of the posted customs usually just use Cherub Rock.

You can get an updated list at http://www.rscustom.net/builds/dlc.xml, save that as "RocksmithToolkitLib.SongAppId.xml" and put it in your toolkit folder.

**Comment by wewlad** [comment]
@ray love you man. Seriously, huge thank you
