### ISSUE TITLE
PC-PS3 converted song sound level too low.

### ISSUE THREAD

**Issue by jacegas** [rscustom/rocksmith-custom-song-toolkit#224]
1. Get official pc dlc song (i.e. seetfake_p.psarc) and perform conversion from PC to PS3 with latest build (2.6.1.0-58ed295c)

Actual result
Song and preview level is too quiet compared to the same song converted with 2.6.0 release build (rev 4174fc7b).

Expecated result
Song level is the same as in release build

2015-05-14 00:26:52.7166 | RocksmithToolkitGUI.Program (INFO) : 
 RocksmithToolkitGUI.Program.Main 
 Version: 2.6.1.0-58ed295c
 OS: Microsoft Windows NT 6.2.9200.0

**Comment by L0FKA** [comment]
I hope you doing this just to test toolkit functionality, but yes, novv toolkit uses another default gain values for song\previevv volume, i.e. -6 vvas for RS1 -6.5 for rs2014, -12 nowdays in toolkit

**Comment by cozy1** [comment]
Dev responded and there is no further followup from originator.
