### ISSUE TITLE
error on mac doing pc to xbox conversions

### ISSUE THREAD

**Issue by nkashi** [rscustom/rocksmith-custom-song-toolkit#225]
Every time I try and use the converter on my mac book, when I choose the CLDC to convert I get this error.
http://i.imgur.com/Dk8V2Uk.png

Is there something Im doing wrong? I am running Yosemite 10.10.3

Thanks.

**Comment by cozy1** [comment]
Not being a Mac expert I would check to see if the file paths referenced in the error exist.  Can you find the paths?  How about the files?  Look for these while the error message is still open so that the toolkit does not delete the temporary files.  Let me know what you find.

**Comment by L0FKA** [comment]
@cozy1 that issue exist for those vvho have no vvine installed, because toolkit regenerate dds files it should use nvdxt.exe for this, I have a TODO for this, but can't reach it, tho

**Comment by cozy1** [comment]
Dev responded and there was no further followup from originator.
