### ISSUE TITLE
Skin Index in pedals

### ISSUE THREAD

**Issue by Dreddfoxx** [rscustom/rocksmith-custom-song-toolkit#226]
According to a couple of official songs (yyx, slither), the SkinIndex in pedals should be a float and not an integer. 

Can be fixed by changing "DLCPackage\Manifest2014\Tone\Pedal2014.cs" and "ToolkitTone\ToolkitPedal.cs" from:

public int? SkinIndex { get; set; }
to:
public float? SkinIndex { get; set; }

**Comment by L0FKA** [comment]
I know(all indexes is float\double values) I added this like that way because I never saw a real use of skin index with decimal point, anyway I'm fine to do this change, gonna commit it now
