### ISSUE TITLE
Unpacking/Importing attr.Tone/XML Issues

### ISSUE THREAD

**Issue by catara** [rscustom/rocksmith-custom-song-toolkit#227]
some CDLC (specially dreddfoxx's) have a blocking issue at unpacking(programmatically)/importing package from the latest build of the Toolkit

e.g. http://customsforge.com/page/customsforge_rs_2014_cdlc.html/_/pc-enabled-rs-2014-cdlc/god-hates-a-coward-r7418

![bug tooklit](https://cloud.githubusercontent.com/assets/1438420/8159572/4b766d96-1368-11e5-80ba-97661ba34a07.png)

can you also please fix toolkit version, as well(0.0.0.0 is no fun) ? :)

**Comment by cozy1** [comment]
Sry for delay.  Looks like you are coder.  Do you have fix?  What should line 421 be?

**Comment by Dreddfoxx** [comment]
Although the program that I released to the community is only for RS1, I also wrote a program for creating CDLC (not released) and there was probably a bug in an old version.  Here a fix for the tool kit (line 484)

 if (data.TonesRS2014.All(t => t.Key != key))
                        {
                            // fix tones names that do not have the correct alphacase for cross matching
                            if (attr.Tone_Base.ToLower() == jsonTone.Name.ToLower() && attr.Tone_Base != jsonTone.Name)
                                jsonTone.Name = attr.Tone_Base;
                            if (attr.Tone_A != null && attr.Tone_A.ToLower() == jsonTone.Name.ToLower() && attr.Tone_A != jsonTone.Name)
                                jsonTone.Name = attr.Tone_A;
                            if (attr.Tone_B != null && attr.Tone_B.ToLower() == jsonTone.Name.ToLower() && attr.Tone_B != jsonTone.Name)
                                jsonTone.Name = attr.Tone_B;
                            if (attr.Tone_C != null && attr.Tone_C.ToLower() == jsonTone.Name.ToLower() && attr.Tone_C != jsonTone.Name)
                                jsonTone.Name = attr.Tone_C;
                            if (attr.Tone_D != null && attr.Tone_D.ToLower() == jsonTone.Name.ToLower() && attr.Tone_D != jsonTone.Name)
                                jsonTone.Name = attr.Tone_D;

                            data.TonesRS2014.Add(jsonTone);
                        }

**Comment by catara** [comment]
please apply the same for the Convert button/workflow line 161 and after
e.g. attr.Tone_C != null
