### ISSUE TITLE
[OS X] - RCST says it requires Mono - I have mono installed.

### ISSUE THREAD

**Issue by cashewguy** [rscustom/rocksmith-custom-song-toolkit#230]
I've got the latest version of Mono (4.0.2.5), and the latest Rocksmith CST from the download page. I can't seem to get them to launch and the error message is pretty entirely unhelpful:

"RocksmithCustomSongToolkit requires the Mono Framework version 2.8 or later."

**Comment by ray** [comment]
What's the output of `mono --version` in Terminal?

**Comment by cashewguy** [comment]
Despite Mono saying it has installed successfully, terminal just says "Command not found".

**Comment by L0FKA** [comment]
@ray use -V svvitch to get version probably script issue, vvith mono 4.0.1 we had coreclr there, so it should be faster now

**Comment by ray** [comment]
It's not a toolkit issue. Command not found indicates that mono wasn't found in the path, so it's not installed correctly.
--version does work with the latest version.

**Comment by cashewguy** [comment]
Then it must be a mono issue, because the installer says it was installed correctly.

**Comment by L0FKA** [comment]
yeah try 4.0.1 version instead, according to this thread threr some major issues with mono installation at OS X

https://forums.sonarr.tv/t/el-capitan-and-sonarr-oops/6274

**Comment by cashewguy** [comment]
Complain? No I came because your program doesn't work and I didn't know why. You don't need to be a prick about it.

**Comment by SanityFox** [comment]
I have a similar issue, except Terminal indicates I have the latest version of Mono 4.2.1

Anyone have a work around to get RocksmihtCustomSongToolkit working with El Capitan?

**Comment by L0FKA** [comment]
Read through #243

**Comment by SanityFox** [comment]
Hmm.. Disabling SIP had not affect. :(

**Comment by zedtux** [comment]
The mono installer install a symbolic link in `/usr/local/bin` while it looks like song toolkit is looking in `/usr/bin`.

Doing `sudo ln -s /Library/Frameworks/Mono.framework/Versions/Current/bin/mono /usr/bin/mono` solved the issue for me.

**Comment by HTmfG** [comment]
I'm lost. I'm on a Mac running MacOS El Capitan 10.11.6 using RockSmith Remastered (Purchased CD) playing through Steam built Oct 12 at 17:51:26 Steam API :v017 Package version 1476379980

I don't know how to do this step:
1. Mono not adding itself to the path properly. Older versions of Mono may work. You might also be able to fix this with sudo ln -s /Library/Frameworks/Mono.framework/Versions/Current/bin/mono /usr/bin/mono 

Terminal says window says: ln: /usr/bin/mono: "Operation not permitted" after I type my password.

I go through the following steps and still nothing helps. Can some one please help me? and tell me what I'm doing wrong or what else I need to do?

I have rebooted to the recovery mode ran the "csrutil disable" command rebooted and installed the latest version of MONO and rebooted to recovery mode and ran the the "csrutil enable" command. Rebooted and I have the same issue when I try to start the toolkit. 

I can see the CDLC in my Rocksmith remastered game. I get through he tuning, but then there is nothing there just an image of speakers and I can play my guitar through the computer, but that's all. I can't even get out of the game without quitting.

Thanks in advance,
-H

ref: https://github.com/rscustom/rocksmith-custom-song-toolkit/issues/243
