### ISSUE TITLE
incomplete #227

### ISSUE THREAD

**Issue by catara** [rscustom/rocksmith-custom-song-toolkit#231]
Unpack fixed, but convert gives the same error.
 please apply the same fix/nullcheck for the Convert button/workflow RocksmithToolkitLibDLCPackage\Arrangements.cs line 161 and after
 e.g. attr.Tone_C != null

**Comment by cozy1** [comment]
Just to followup, was this ever fixed/changed?

**Comment by catara** [comment]
Unpack fixed, but convert gives the same error.
please apply the same fix/nullcheck for the Pc2PS3 Convert button/workflow RocksmithToolkitLibDLCPackage\Arrangements.cs line 161 and after
e.g. attr.Tone_C != null
http://customsforge.com/page/customsforge_rs_2014_cdlc.html/_/pc-enabled-rs-2014-cdlc/god-hates-a-coward-r7418

It works in my convert code(https://github.com/catara/rocksmith-custom-song-toolkit/blob/master/RocksmithToolkitLib/DLCPackage/Arrangement.cs) which is just a replication of the previous import issue Fix
https://github.com/rscustom/rocksmith-custom-song-toolkit/issues/227

**Comment by cozy1** [comment]
Fixed here https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/14f5fa47066c0530e3dc8cdc2b4b36ab84d644a4
