### ISSUE TITLE
RS1 -> RS2 Conversion Error

### ISSUE THREAD

**Issue by Jorgixhallo** [rscustom/rocksmith-custom-song-toolkit#233]
Another error on conversion. This time the exception is not caught by rscustom, but by the system.

http://www.filedropper.com/rstoolkit2015-07-21

hot .dat (110), but the same error on several. I would like to understand more of the overall code. Any tip for debugging in order to help you guys with some code?

**Comment by L0FKA** [comment]
so it was fixed? specify commit please
