### ISSUE TITLE
Cannot be built from a Mac

### ISSUE THREAD

**Issue by hajdbo** [rscustom/rocksmith-custom-song-toolkit#236]
The source cannot be built from a Mac right now (Xamarin or xbuild). A few PreBuild/PostBuild scripts are Windows-only.

**Comment by hajdbo** [comment]
proposed patch: https://github.com/rscustom/rocksmith-custom-song-toolkit/pull/237

**Comment by L0FKA** [comment]
@hajdbo, please test last changes I've made, it should work too, but I also added small sh script to build Mac .app bundle haven't tested it, but it should work, packing to tar.gz is a bit redundant, you can comment it out if you want.

**Comment by hajdbo** [comment]
works fine
