### ISSUE TITLE
Error converting on a case-sensitive filesystem

### ISSUE THREAD

**Issue by hajdbo** [rscustom/rocksmith-custom-song-toolkit#240]
GetPathName() returns camelcase like "MacOS" to build a path, where the directory is often "macos".

About half the code calls GetPathName().ToLower(), but not Packer.cs.

**Comment by L0FKA** [comment]
Please highlight critical sections about paths I'll fix whole code to match this criteria then.

**Comment by L0FKA** [comment]
@hajdbo I set this flag for mono at Mac OS, so this should fix path issues for now, also added optimizations to the toolkit so it reacts faster than native NET here :lol:

**Comment by cozy1** [comment]
Dev responded and there was no further followup from originator.
