### ISSUE TITLE
Issue Custim Song Toolkit Locksmith 2014 ( OS X The Captain ) 

### ISSUE THREAD

**Issue by PhonneyHook** [rscustom/rocksmith-custom-song-toolkit#245]
When I open the Custom Song Toolkit it says to me that i have to upgrade to 2.4 version of Mono Framework and i download it , install it and it keeps appearing the same issue , i dowloaded again the toolkit and the mono framework, i unistalled all but it keeps appearing the same error.. Guys what can i do???

**Comment by ray** [comment]
See my comments on #243
