### ISSUE TITLE
Error using CDLC2Tab

### ISSUE THREAD

**Issue by davidlavy88** [rscustom/rocksmith-custom-song-toolkit#247]
Hello,

I downloaded and updated the Toolkit, but whenever I click the Convert button in my CDLC2Tab tab I get this error. http://imgur.com/v6ZN2BC. I'm using Windows7 on a 64bit computer and my folder is on my desktop.
Please help. Also this is my log generated 

https://docs.google.com/document/d/1UCD01S8_bxxOfu3L7vWFUkcOmGvevXt7dz9l-DyBnLE/edit?usp=sharing

Thanks.

**Comment by cozy1** [comment]
@davidlavy88 The error message is telling you that RocksmithToTabLib.dll is missing.  Delete the toolkit folder and download a fresh copy.  Make sure that RocksmithToTabLib.dll is present in the fresh install.

**Comment by cozy1** [comment]
Dev responded and there was no further followup from originator.
