### ISSUE TITLE
Control the display of a chord with "chordDensity" tag

### ISSUE THREAD

**Issue by Chlipouni** [rscustom/rocksmith-custom-song-toolkit#248]
In the current release, a chord is fully displayed only if it is the first one of the handshape whatever the value of the "chordDensity" tag.
As a handshape is used to define the finger positions, we can't have several variations of a chord inside the same handshape, because only the first one is fully displayed (for the following ones, only a repeated chord box is displayed).

In the "master/RocksmithToolkitLib/Sng/Sng2014FileWriter.cs" file at line 1023 : 
```C#
    // add STRUM to chords
    if (fp1[id].StartTime == n.Time && n.ChordId != -1)
        n.NoteMask |= CON.NOTE_MASK_STRUM;
```
Replacing these few lines by the following ones :
```C# 
    // add STRUM to chords if highDensity = 0 and chordId != -1
    if ((n.NoteMask & CON.NOTE_MASK_HIGHDENSITY) != CON.NOTE_MASK_HIGHDENSITY && n.ChordId != -1)
        n.NoteMask |= CON.NOTE_MASK_STRUM;
```
Offers a way to have the total control of which chord to display or not by simply setting the chordDensity tag.

**Comment by L0FKA** [comment]
So if highDensity set to 0 we'll see a hand shape? "strum" attribute used to control Density of the chord?
Can I have link to test files you've got I'd like to play around with this and you can submit pullrequest if you'd like to

**Comment by Chlipouni** [comment]
Hi Alex,

  The "strum" flag seems to control the full display of chord notes (or
only the repeated chord box).
  So I modified the condition to "strum" the chord only when the
"highDensity" = 0

  There may have been a reversal between the "strum" and "highDensity"
flags in the Toolkit code ...

  You can download the zip file which contains a few examples to test it :
  - HandShape HD : for highDensity variations on a standard power chord
iteration (the first occurrence has a highDensity = 1 for testing purpose
only)
  - HandShape V : for "HandShape phrases" testing with chord variations
inside and "highDensity" to control which one to display or not
  - HandShape A : for "HandShape phrases" testing with only single notes
inside (there is no chord in this example, so you can ignore it)


https://drive.google.com/file/d/0Bx3RFcxnp8nWaW1XQWtHZjE5Z0E/view?usp=sharing

  Each example has its own package (and its own RST XML file).

  I do not give you the EOF files because it will override the
modifications I have made on the "chordDensity" tags.

  This new feature will be great to simplify the handShapes management in
EOF and DDC tools ...

Thank you


2016-01-02 10:32 GMT+01:00 L0FKA <notifications@github.com>:
