### ISSUE TITLE
CF.AudioTools fail to transcode rs1 AK_RIFF container to OGG

### ISSUE THREAD

**Issue by L0FKA** [rscustom/rocksmith-custom-song-toolkit#253]
I think I should release customization for this lib with all changes I planned, as for now allow old ww2ogg+revorb way...

**Comment by cozy1** [comment]
I have some other changes to commit that are unrelated to this.  Would you like me to comment out the AudioTools.dll usage and go back to old exe way for now or will you do?  How about the ImageTools.dll should that be reverted to exe as well?

**Comment by L0FKA** [comment]
I'll do, also didn't test image tools entirely(It has decent compression quality like nvdxt).

**Comment by cozy1** [comment]
CF.AudioTools is now deprecated from toolkit.  We can close this.

**Comment by L0FKA** [comment]
I'd like to dig into my own implementation of this, still ti would take me some time so not a big deal :)
yeah we could close some other issues too...
