### ISSUE TITLE
Code Signing Certificate Has Expired

### ISSUE THREAD

**Issue by cozy1** [rscustom/rocksmith-custom-song-toolkit#256]
ray, please update cert so that AppVeyor builds.  https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/26c265dd20f56926045efea3a36555b8639dae03

Thanks

**Comment by L0FKA** [comment]
Thees guys is way more active ;)

**Comment by cozy1** [comment]
Thank you.

**Comment by ray** [comment]
It should be good now, last build was successful
