### ISSUE TITLE
RS ToolKit Error 2016.07.04

### ISSUE THREAD

**Issue by ShrillBear52** [rscustom/rocksmith-custom-song-toolkit#257]
I haven't created  songs for months ,recently I've got an issue with geneating the wav wwise file,so when I hit generate button in the toolkit I got a message what says there is a compatible issue with the latest Wwise and I have to use an earlier version,but when I use and earlier version I get this message

http://tinypic.com/r/2i05bfn/9

**Comment by L0FKA** [comment]
Re-download toolkit, it seems that it lost it's wwise 215 tar file, it should be good for Wwise v2015.1.6 build 5553, the latest I checked..

PS: Kelly didn't help to solve this I guess :D

**Comment by ShrillBear52** [comment]
It's still bad if I re-download and update it,even with the newest version!

**Comment by L0FKA** [comment]
You may have it blocked by Antivirus, like avast or so, try disabling it's proactive defense or add rstk to ignore list, also specify your wwise version or use one I mentioned to be sure it's 100% should work.

**Comment by L0FKA** [comment]
You may have it blocked by Antivirus, like avast or so, try disabling it's proactive defense or add rstk to ignore list, also specify your wwise version or use one I mentioned to be sure it's 100% should work.

**Comment by ShrillBear52** [comment]
No changes,the only thing that allowd me to generate the rocksmith file is re-downloading the toolkit but not update it.....
