### ISSUE TITLE
Issue New Release Version of Toolkit

### ISSUE THREAD

**Issue by cozy1** [rscustom/rocksmith-custom-song-toolkit#258]
@ray How do we get the release version of the toolkit updated?  Users have repeatedly asked me about getting the current beta to be issued as the new release.

If nothing else could we take down the current release which is very old and buggy?

Thanks

**Comment by ray** [comment]
Go to releases and draft a new release.
Tag it with the current version (2.6.1.0), and give it a title/description similar to previous releases.
Once you publish the release the binaries should get attached automatically.

Once that's done you'll want to increment the version number for new beta builds in the various AssemblyInfo's.
Since it's been awhile since the last release you might want to bump it up before the release too.

**Comment by cozy1** [comment]
OK ... will do.

**Comment by cozy1** [comment]
New Release Version 2.7.0.0 image holder

![2 7 0 0](https://cloud.githubusercontent.com/assets/6805057/17595537/1051f6a2-5fb3-11e6-8d88-42bde5c231a0.jpg)

**Comment by fabianosan** [comment]
I asked about new release many times ago... Thanks for the release.

**Comment by cozy1** [comment]
Me too!  That's why I took care of it. 

AppVeyor is being slow right now ... so the beta 2.7.1.0 has not updated yet.   Release seems good.

**Comment by cozy1** [comment]
@ray  Thanks for guidance.  All seems to be working again including both release and beta builds.

**Comment by L0FKA** [comment]
Good work on putting this up :)

**Comment by cozy1** [comment]
@L0FKA  "I'm sure we can't list all the changes made up from plast release, haha"
About that, if there are significant changes that you know of that I left off accidentally I will be glad to edit the release page notes.  Just let me know what you would like added.

**Comment by L0FKA** [comment]
I'd like to have news at toolkit site to be updated with new release tweet ;)

I'll think of it also need to create new thread on sites we support

**Comment by ray** [comment]
There used to be a section on the site where you could log in to update it but it got removed when the site was rebuilt.

Everyone should now have access at https://github.com/rscustom/website to make changes to the news section, just edit the news.md and follow the format of the other entries.

**Comment by cozy1** [comment]
@ray Thanks. Working very nicely.  I updated the Latest News section.  Took me a bit to figure out how to do links in MD.

**Comment by Unleashed2k** [comment]
@ray & others I was wondering if it's possible that CustomsForge could acquire/help this project at all. It would run exactly the same but we could update the website / etc. If any area is lacking we can find spots to fill. Let me know what you think and if you have any questions or concerns.

**Comment by fabianosan** [comment]
Good job...

"Added so much more!" sounds really cool to me, haha.

Good job guys, toolkit is really better.
