### ISSUE TITLE
On Sierra Always Mono required notification

### ISSUE THREAD

**Issue by JRRN** [rscustom/rocksmith-custom-song-toolkit#260]
On macOS Sierra always require Mono 2.8 or latter.

Mono is downloaded and installed.

**Comment by L0FKA** [comment]
@JRRN are you able to tweak this launch script to avoid that annoying message? 
(https://github.com/rscustom/rocksmith-custom-song-toolkit/blob/master/RocksmithTookitGUI/bin/RocksmithCustomSongToolkit.app/Contents/MacOS/RocksmithCustomSongToolkit)
do you able to run it anyway?

**Comment by kulagun** [comment]
I get the same error "RocksmithCustomSongToolkit" requires the mono framework version 2.8 or latter. Mono Framework not installed or too old. I have the latest version installed.

**Comment by L0FKA** [comment]
So noone able to fix this issue for you guys, sorry bout  that..
Maybe @hajdbo could fix this?

**Comment by hajdbo** [comment]
not before several weeks, sorry

**Comment by NicosKaralis** [comment]
So, I was having this problem. I ran the script @L0FKA asked and also the same message. So I opened the script and started debugging it.

    $ sw_vers -productVersion
    > 10.12.1

My problem is that the version of the SO is not 10.11.*

    if [[ `sw_vers -productVersion` = "10.11"* ]]

Changing it to ``if [[ `sw_vers -productVersion` = "10.12"* ]]`` worked for me and now the `RocksmithCustomSongToolkit.app` opens and closes.

Am I missing something?

**Comment by L0FKA** [comment]
@NicosKaralis, if you want to commit it by yourself please do otherwise I may Set another check to make sure it's greater than specified instead hard-coding exact same version, right?

**Comment by Solovgeo** [comment]
doesn't work, same notification, and when I just tried to execute script, it's writting 
```
noname$ /Users/noname/Downloads/rocksmith-custom-song-toolkit-master/RocksmithTookitGUI/bin/RocksmithCustomSongToolkit.app/Contents/MacOS/RocksmithCustomSongToolkit ; exit;
/Users/noname/Downloads/rocksmith-custom-song-toolkit-master/RocksmithTookitGUI/bin/RocksmithCustomSongToolkit.app/Contents/MacOS/RocksmithCustomSongToolkit: line 27: MAC_VERSION_MINOR: command not found
Current Mono version: v4.6.2
Cannot open assembly 'RocksmithCustomSongToolkit.exe': No such file or directory.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...126 completed.
```

**Comment by L0FKA** [comment]
Adopting another mono script for toolkit launcher >_> will commit asap

**Comment by Solovgeo** [comment]
bring back 
`-APP_PATH=`echo $0 | awk '{split($0,patharr,"/"); idx=1; while(patharr[idx+3] != "") { if (patharr[idx] != "/") {printf("%s/", patharr[idx]); idx++ }} }'``
and it will work

**Comment by L0FKA** [comment]
@Solovgeo, please can you share screen or terminal output log, I'm doing this almost blindly :(
is it launching for you now without issues? is it just fail to convert custom file?

thanks!

**Comment by Solovgeo** [comment]
<img width="637" alt="2016-11-29 19 28 53" src="https://cloud.githubusercontent.com/assets/17564316/20723319/56600d24-b66a-11e6-9247-627b98a55891.png">
<img width="651" alt="2016-11-29 19 29 18" src="https://cloud.githubusercontent.com/assets/17564316/20723323/5af78510-b66a-11e6-89cf-a88fc107c9fe.png">
<img width="649" alt="2016-11-29 19 29 34" src="https://cloud.githubusercontent.com/assets/17564316/20723326/5d791f60-b66a-11e6-8be5-ce592e7fd52c.png">

I can click on run (using restart to get on screen), it almost every buttonclick send this exceptions, and fail on converting

**Comment by L0FKA** [comment]
Congrats with getting mac :)
https://eclecticlight.co/2016/06/16/macos-sierra-will-break-many-installers-and-updaters/

It moves app to the protected path and it's unable to get access so I guess it required more tweaks to launcher then I can implement.

Maybe try run using sudo command (admin mode), I'd like to have live-chat with testers to eliminate issues more efficiently

**Comment by L0FKA** [comment]
[Read this article to figure out issues with toolkit on mac](http://customsforge.com/topic/33889-how-to-add-custom-songs-on-mac/?p=81067)

**Comment by L0FKA** [comment]
thread necro but I'm closing this since we've got mac port with toolkit and I;m not sure We'll bother with native sierra issues any how soon along with other software devs you may find havveing fun with that new OS :P

**Comment by ainthek** [comment]
I have the same Unauthorized.... error message. Lofka, does it mean you do not support OSX anymore and we all shell convert to wine ? or someone resolved this issue ? Thanx

**Comment by L0FKA** [comment]
@ainthek I'm dropping mono until those guys gorw into 1:1 standard .Net functionality w\o bugs like this. and probably I'll be gone from this project till that happens, if someone with mac and will to tackle mono is here I can merge your pull requests %username%

Wine port works like charm so I'll probably stick with it, still gotta thinker how to reduce package size a bit more. Dark Seph did it as dmg already... hm.

**Comment by ainthek** [comment]
Please where can we find the mentioned Wine port ?
also this link is not working:  http://customsforge.com/topic/39922-latest-rstoolkitwine-releases-10-27-2017/
