### ISSUE TITLE
911: Rocksmith CDLC .dll

### ISSUE THREAD

**Issue by Unleashed2k** [rscustom/rocksmith-custom-song-toolkit#261]
The Rocksmith 2014 Remastered officially broke CDLC. 
Does anyone know who originally created the .dll workaround?

**Comment by ray** [comment]
I was worried that was going to happen. I'll take a look tonight, but if it's not a quick fix we might have to start reverse engineering again.

**Comment by Unleashed2k** [comment]
The appid has changed for the patch, just a suggestion but that could possibly be the issue.

**Comment by Unleashed2k** [comment]
We're doing some work on our end and will update you with our findings. So far we can see that CDLC loads up to the tuner. Nothing loads after. appIDed Official DLC still works (testing purposes only) so it's not a duplicate DLC issue.

**Comment by Unleashed2k** [comment]
Pretty much it comes down to the injector/dll needing an update.

**Comment by fabianosan** [comment]
@Ray, do you have the DX3D.dll code? Or we have only the Injector code?

I believe that I have the old Google Groups thread about the dlc signature patch in my mail.

**Comment by ray** [comment]
No we don't have the code for it. The old group is at https://groups.google.com/forum/#!forum/rocksmith-custom-song-project though I don't recall the source ever being shared

**Comment by Dreddfoxx** [comment]
I've never seen the source for it.

**Comment by Dreddfoxx** [comment]
got it working :). I'll post a fix shortly.

**Comment by Unleashed2k** [comment]
@Dreddfoxx we got it working too haha we're releasing a fix too, do you have just  DLL copy of it?

**Comment by Dreddfoxx** [comment]
Cool, if you're releasing a fix, I won't bother :).

**Comment by fabianosan** [comment]
> got it working :). I'll post a fix shortly.

Good news Dredd.
Only just now I got my house to help in the analysis.

We have the D3DX9_42.dll and RSInjector, in whitch you are working on?

**Comment by Unleashed2k** [comment]
We still need the DLL fix, but we fixed injector on PC and have it released

**Comment by fabianosan** [comment]
Good news, I saw the thread.
Please update the RSINJECTOR code...

**Comment by Unleashed2k** [comment]
I've updated our topic at CF to include the DLL fix

**Comment by fabianosan** [comment]
Wow, you'really so fast. Post the DLL code on git hub for all, so when it happen again, others can help with less effort.

**Comment by Unleashed2k** [comment]
​​I'm going to try to get him to do that, he uploaded it on CF. Let me PM him.

**Comment by Unleashed2k** [comment]
@fabianosan here you go: https://github.com/geneccx/RSCDLCEnabler

**Comment by fabianosan** [comment]
> @fabianosan here you go: https://github.com/geneccx/RSCDLCEnabler

Good job, thank you very much.
