### ISSUE TITLE
RS Remaster Crash when there's more than 5 arrangement

### ISSUE THREAD

**Issue by Firekorn** [rscustom/rocksmith-custom-song-toolkit#263]
The remaster update that change the way to access bonus/alternate arrangement is now crashing when there's more than 5 playable arrangement.

Would it be possible for the toolkit to add at least a warning about it when there's 6 or more playable arrangement or to simply limit directly the number of arrangement a creator can add into the toolkit to avoid any unwanted crash?

**Comment by Firekorn** [comment]
The full discussion about this issue on CF with some adjustment regarding Metronome arrangement : http://customsforge.com/topic/33494-number-of-arrangement-available-in-rs-remastered/

**Comment by cozy1** [comment]
@Firekorn  Added a user warning when "Generate" button is press if the CDLC will exceed the arrangement limit.  https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/1fb0b8317b11b635b6958d16ec64dd3b801ed02f  Please confirm feature is working.

**Comment by Firekorn** [comment]
@cozy1 in a2aa508a, vocals are counted as playable arrangement but they shouldn't.

**Comment by cozy1** [comment]
@Firekorn Fixed bug in arrangement count warning message.  https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/21d7bec7c4ede54d1b62185d55216e9095c32b67  Please confirm fix is working.  Thanks

**Comment by Firekorn** [comment]
Yep everything seems fine for me 👍
