### ISSUE TITLE
Broken link for DDC help

### ISSUE THREAD

**Issue by Firekorn** [rscustom/rocksmith-custom-song-toolkit#267]
![ddclinkerror](https://cloud.githubusercontent.com/assets/1771169/19417380/965b5456-93ab-11e6-9adb-b3d11dab5a8b.png)
When clicking on the link in the DDC tab

**Comment by L0FKA** [comment]
It seems non of the browsers in list so it fails, need to cover it with tests, thanks for the input!

**Comment by L0FKA** [comment]
It seems non of the browsers in list so it fails, need to add more safty checks, thanks for the input!

**Comment by Firekorn** [comment]
Works fine in the 86e68021 beta

**Comment by L0FKA** [comment]
I have fixed Edge support for win10, gonna push it tonight :)
