### ISSUE TITLE
Tone names containing an underscore

### ISSUE THREAD

**Issue by papillon-rs** [rscustom/rocksmith-custom-song-toolkit#268]
Tones are saved without underscore when editing them in the toolkit - this has been discovered by iminashi - see topic at http://customsforge.com/topic/33369-tone-names-containing-an-underscore-broken-in-the-latest-build/?hl=underscore

**Comment by cozy1** [comment]
@papillon-rs  Please confirm tone naming issue is fixed with [latest beta release](https://www.rscustom.net/download/611/rstoolkit-2.7.1.0-450f558b-win.zip).  Thanks for issue report.

**Comment by papillon-rs** [comment]
I've created a custom with modifying tones (having underscores in their names) and the custom works fine in RS remastered.
For me bug seems to be fixed and if anybody has a constellation where this still causes problems should reopen it or add a new report. Thx for the fix and the good work on all RS related tools.
