### ISSUE TITLE
Implement backup before update for beta branch

### ISSUE THREAD

**Issue by L0FKA** [rscustom/rocksmith-custom-song-toolkit#269]
I'd like to have some lvl of protection for users who used beta branch as main toolkit so if it has critical stat like bugfix #4 till #8 we could restore previous build installed.

Updater improvement, still I'd like to find decent .NET updater class\module which has bestpractices already in it :)

**Comment by cozy1** [comment]
Does [this](https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/1f3374c7b4cb15eacbb2d8370642c1a8632bb078) rev and [this](https://github.com/rscustom/rocksmith-custom-song-toolkit/blob/1f3374c7b4cb15eacbb2d8370642c1a8632bb078/RocksmithToolkitUpdater/AutoUpdaterForm.cs#L656)  address your issue so we can close it?

**Comment by L0FKA** [comment]
Tests Is the only way I could validate that, but we don't have one so let's hope it works
