### ISSUE TITLE
[RS2014 remastered] Play counter in learn a song mode does not increment

### ISSUE THREAD

**Issue by papillon-rs** [rscustom/rocksmith-custom-song-toolkit#270]
I think the issue is known, but nobody has opened a report.
The play counter increments in score attack but not in learn a song.

**Comment by Firekorn** [comment]
Note that this doesn't happen on CDLC with DD (easier made by hand or by DDC) so it doesn't seems related to the toolkit itself.

Note that before the remaster any CDLC without any section would have this issue too and now the requirements to have the play counter actually work seems to have changed a bit.

**Comment by cozy1** [comment]
Will look at as time permits but for now seems like non-toolkit issue.
