### ISSUE TITLE
Bass "pickedness" not reflected in Score Attack mode

### ISSUE THREAD

**Issue by iminashi** [rscustom/rocksmith-custom-song-toolkit#272]
Even if you check the bass as picked, it will still say "Bass (Fingered)" in Score Attack.

How to fix:

The following attribute needs to be written into the manifest .hsan file for the bass arrangement:

"BassPick": 1,

**Comment by cozy1** [comment]
@iminashi  Please confirm fix is working.  Thanks

**Comment by iminashi** [comment]
Fix is working.
