### ISSUE TITLE
Can't open on sierra

### ISSUE THREAD

**Issue by mdarveau** [rscustom/rocksmith-custom-song-toolkit#273]
I get the following message when launching `RocksmithCustomSongToolkit.app`:
![image](https://cloud.githubusercontent.com/assets/390071/20874440/05d225d0-ba80-11e6-8f73-2e4e756542bb.png)

Anything I can check to see what's the cause?

Thanks!

**Comment by L0FKA** [comment]
I may lost -x permission for the launcher script, I don't think I can help you guys at all, I have no mac any where near (maybe I'll get one in near 5 yrs :D)

but for now I can suggest trying disable Gatekeeper
`sudo spctl --master-disable`

you can enable it after using this command
`sudo spctl --master-enable`

or also try set executable flag to all .app bundle contents
http://superuser.com/questions/898124/the-application-someapp-app-can-t-be-opened

cheers

**Comment by mdarveau** [comment]
`chmod +x RocksmithCustomSongToolkit.app/Contents/MacOS/*` did the trick.

Now I have the issue described in https://github.com/rscustom/rocksmith-custom-song-toolkit/issues/260.

**Comment by L0FKA** [comment]
Would be nice to have more info about 260 
you mean permission issue or mono version required popup?

**Comment by mdarveau** [comment]
The initial popup "The application (...) can't be opened." was caused by a permission issue. Then I get the "mono version required" popup. I tried everything listed in #260 but I can't get it to open.
