### ISSUE TITLE
Mono and song took kit not working with RockSmith 2014 Remastered

### ISSUE THREAD

**Issue by HTmfG** [rscustom/rocksmith-custom-song-toolkit#274]
I'm lost. I'm on a Mac running MacOS El Capitan 10.11.6 using RockSmith Remastered (Purchased CD) playing through Steam built Oct 12 at 17:51:26 Steam API :v017 Package version 1476379980

I don't know how to do this step:

Mono not adding itself to the path properly. Older versions of Mono may work. You might also be able to fix this with sudo ln -s /Library/Frameworks/Mono.framework/Versions/Current/bin/mono /usr/bin/mono
Terminal says window says: ln: /usr/bin/mono: "Operation not permitted" after I type my password.

I go through the following steps and still nothing helps. Can some one please help me? and tell me what I'm doing wrong or what else I need to do?

I have rebooted to the recovery mode ran the "csrutil disable" command rebooted and installed the latest version of MONO and rebooted to recovery mode and ran the the "csrutil enable" command. Rebooted and I have the same issue when I try to start the toolkit.

I can see the CDLC in my Rocksmith remastered game. I get through he tuning, but then there is nothing there just an image of speakers and I can play my guitar through the computer, but that's all. I can't even get out of the game without quitting.

Thanks in advance,
-H

ref: #243

**Comment by cozy1** [comment]
[Have a look on CF](http://customsforge.com/topic/10547-how-to-add-custom-songs-on-mac/#entry80868) for solutions to issues with Mac version of toolkit.

**Comment by cozy1** [comment]
Here is how to resolve:
https://github.com/rscustom/rocksmith-custom-song-toolkit/issues/276
https://github.com/rscustom/rocksmith-custom-song-toolkit/issues/262
