### ISSUE TITLE
[MAC] awk command change broke launch

### ISSUE THREAD

**Issue by JustinAiken** [rscustom/rocksmith-custom-song-toolkit#275]
The `awk` command change in 8c786b1e0846d62019afc4eb94adb53b050c9ea6 broke it for me (10.11.6)

```bash
export foo=/Applications/RocksmithCustomSongToolkit.app/Contents/MacOS/RocksmithCustomSongToolkit
OLD_WAY=`echo $foo | awk '{split($0,patharr,"/"); idx=1; while(patharr[idx+3] != "") { if (patharr[idx] != "/") {printf("%s/", patharr[idx]); idx++ }} }'`
NEW_WAY=$(echo "$foo" | awk '{split("$0",patharr,"/"); idx=1; while(patharr[idx+3] != "") { if (patharr[idx] != "/") {printf("%s/", patharr[idx]); idx++ }} }')

echo "foo=$foo"
echo "OLD_WAY=$OLD_WAY"
echo "NEW_WAY=$NEW_WAY"

# Output:
foo=/Applications/RocksmithCustomSongToolkit.app/Contents/MacOS/RocksmithCustomSongToolkit
OLD_WAY=/Applications/RocksmithCustomSongToolkit.app/
NEW_WAY=
```

If I just swap out the one line in the latest build, then it up and works (`Current Mono version: v4.0.4`)

I also use `zsh` instead of `bash`, maybe that's it?

**Comment by L0FKA** [comment]
Yes it may be cause of that(thanks to no standardization in *nix world), but then you\we should change all calls back to `` notation or is it important for calls like this?

**Comment by JustinAiken** [comment]
>  but then you\we should change all calls back to `` notation or is it important for calls like this?

For my system, it was only that one line - the other `$()`'s were fine... 

I think it might be that the `$()` way is literally passing "$0" instead of the variable `$0` to awk with that notation?

**Comment by JustinAiken** [comment]
....but aside from that `awk` command, that commit did fix mono for me - is the first release I was actually able to run instead of having to use VirtualBox 😄

**Comment by L0FKA** [comment]
@JustinAiken got it, committing back this fix, thank you for the input. 
:)

**Comment by L0FKA** [comment]
btw I've got reports on sierra about access issues, maybe you know how to fix it aside external command (set exec flags) ?

alos VirtualBox solution would be much stable because we use lot's of windows cli apps to convert audio and graphics...

**Comment by JustinAiken** [comment]
Okay, I was a bit off!  Issue wasn't the `$()`, it's the quotes around the `$0` args...

```bash
# Works:
APP_PATH=`echo $0   | awk '{split($0,patharr,"/"); idx=1; while(patharr[idx+3] != "") { if (patharr[idx] != "/") {printf("%s/", patharr[idx]); idx++ }} }'`
# Also works:
APP_PATH=$(echo $0   | awk '{split($0,patharr,"/"); idx=1; while(patharr[idx+3] != "") { if (patharr[idx] != "/") {printf("%s/", patharr[idx]); idx++ }} }'$)
# Doesn't work:
APP_PATH=`echo "$0" | awk '{split("$0",patharr,"/"); idx=1; while(patharr[idx+3] != "") { if (patharr[idx] != "/") {printf("%s/", patharr[idx]); idx++ }} }'`
# Also doesn't work:
APP_PATH=$(echo "$0" | awk '{split("$0",patharr,"/"); idx=1; while(patharr[idx+3] != "") { if (patharr[idx] != "/") {printf("%s/", patharr[idx]); idx++ }} }'$)
```

So 92945446080c2d1ee43c93c34ae96698b32db1d6 doesn't fix it unfortunately, but just dropping the quotes around `$0` (in both places) will do the trick!

**Comment by JustinAiken** [comment]
> btw I've got reports on sierra about access issues, maybe you know how to fix it aside external command (set exec flags) ?

*continues avoiding Sierra because of issues like this 😛 *

**Comment by JustinAiken** [comment]
That did the trick! 👍
