### ISSUE TITLE
2.8.0.0 Release Version of Toolkit for Remastered 

### ISSUE THREAD

**Issue by cozy1** [rscustom/rocksmith-custom-song-toolkit#278]
This is a placeholder which is used for cloud.githubusercontent.com image storage.

![2 8 0 0](https://cloud.githubusercontent.com/assets/6805057/22183275/866477be-e07f-11e6-873e-9d5922dc8d0c.jpg)

**Comment by cozy1** [comment]
@ray It has been too long.  I am trying to issue a release version of toolkit for Remastered.   How do I get the 'Downloads' panel on www.rscustom.net server to point to the correct 2.8.0.0 Release (3d133c61) version?  Everything else seems ok.  Thanks

**Comment by ray** [comment]
It looks like there were multiple releases for the same tag under different commits which isn't a case the site was made to handle. I've updated the db manually for now

**Comment by cozy1** [comment]
I messed up a little.  Thanks
