### ISSUE TITLE
Song BPM not importing when adding an arrangement

### ISSUE THREAD

**Issue by Firekorn** [rscustom/rocksmith-custom-song-toolkit#279]
I'm not sure when that function broke as i haven't really paying much attention to that field (and i'm sure if it has any impact on the CDLC anyway) but i guess it could maybe be useful one day to have the correct info pulled from the xml arrangement and i recall that was the case some time ago.

Sorry that i can't give any timeline on when it worked/broke.

**Comment by cozy1** [comment]
Fixed a bug that prevent tempo from being adding correctly when manually adding XML arrangements to CDLC Creator.

https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/703aa24bebf63b3eb2febda4d0f58ea0d1448fc5
