### ISSUE TITLE
Order in the DLC folder.

### ISSUE THREAD

**Issue by MartinBombarder** [rscustom/rocksmith-custom-song-toolkit#281]
After creating lots of songs it would be good to have some feature that would allow everyone to sort and change file names of those DLC files.

**Comment by L0FKA** [comment]
Please use CFM for managing songs, look here: http://ignition.customsforge.com/cfsm 
(cf account required since it has extra features for site specific routines...

**Comment by cozy1** [comment]
@MartinBombarder  You can also use CGT (Custom Game Toolkit) to manage, rename and sort your CDLC into folders by Artist Name.  [Have a look here.](goo.gl/X4wGOA)

**Comment by MartinBombarder** [comment]
Sorry, I couldn't find any tool that can do that. Thank you for the links.
