### ISSUE TITLE
v2.8.x does not prompt to install mono framework on Sierra

### ISSUE THREAD

**Issue by malisit** [rscustom/rocksmith-custom-song-toolkit#282]
I use macOS Sierra, I first tried to run 2.8.x and it did not prompt anything so I tried 2.6.x and realized that mono framework wasn't installed. I think this issue should be fixed in order to let user know what is the thing that's causing the application crash.

**Comment by L0FKA** [comment]
Please try this beta, whick is a bit huge, but should have 100% functionality :)
https://drive.google.com/open?id=0B6zOE-7JCxwjV3pJbkU5eDEyTG8

build it with VM so It may won't work, but let me know if it's ok or not

sierra isn't really supported by the way It's too fresh even for mono framework tho...
El Capitan is the mos stable release right now.+

**Comment by malisit** [comment]
This one's not starting at all but the last build already is working for me. Thanks!
