### ISSUE TITLE
Repack AppId fails (Mac and PC)

### ISSUE THREAD

**Issue by kfeuerherm** [rscustom/rocksmith-custom-song-toolkit#283]
rstoolkit-2.8.0.0-3d133c61-mac installed today. Every attempt to repack the App ID fails. The same seems to happen with the PC version running under Parallels.

The only way to do it seems to be to convert to another platform type and convert back (or start with a different type to begin with).

After converting and converting back, I tried it again, same problem. Also tried with multiple files, no difference.

<img width="476" alt="screen shot 2017-03-26 at 13 11 36" src="https://cloud.githubusercontent.com/assets/11524091/24333477/97b1e7c6-1226-11e7-95e0-47989e3f3601.png">

**Comment by L0FKA** [comment]
Is it latest nighty\beta build? could you link me a psarc you're tying to change appid and if it's just common case I think I'll get this issue form n^2 users as well, no?
If you'd like to help us with mac os builds we're trying to build let us know we need some more native mac users right now we've got only 2 :)

**Comment by kfeuerherm** [comment]
No, it's the Latest Release at rscustom.net
<img width="539" alt="screen shot 2017-03-26 at 16 37 22" src="https://cloud.githubusercontent.com/assets/11524091/24335329/f6db7bb4-1248-11e7-9545-7a06a764fde4.png">
I downloaded the builds for Windows and Mac. I’ve found in the past that the Mac version frequently doesn’t work (I tried unpacking files for example, no go) so when I have problems I try the Windows version and usually I’m ok. (Of course this won’t work for most Mac users…)

Here's the link to the Amy Winehouse file mentioned above: https://www.dropbox.com/s/a8zcmvpt7gxh91j/Amy-Winehouse_Rehab_v1_DD_p.psarc

Yeah, I’m surprised if I’m the only one who finds a problem, makes me wonder, you’d think lots of people would have the issue. I’m on macOS Sierra if that helps.

I’m happy to help any way I can, not sure what you’d want me to do?

**Comment by L0FKA** [comment]
@kfeuerherm ok, that file is just regular html page you can open it in any txt editor just select all files in filter menu to see it's a xml format... yoiu should Download actual psarc file, somehow you've got wrong file, customs. even small one couldn't me smaller than 500 kb (I've got 30 sec song about that amount of space, mostly 3-4 minute songs ia like 5 mb long, be sure to DL correct one ;) )

about testing all you need to do is dl beta build for mac (I'll provide link for that) and dell us if it works at all for you... tho if you've got traffic limitaions I don't want to bother you with getting 1gig files or so while we doing research...

**Comment by L0FKA** [comment]
@kfeuerherm works just fine on windows, with file provided, for beta build and release, please describe more in depth how you're doing this step ?

**Comment by JustinAiken** [comment]
> If you'd like to help us with mac os builds we're trying to build let us know we need some more native mac users right now we've got only 2 :)

Here's one of us reporting that repacking that Amy Winehouse worked perfect, first try...

- El Capitan 10.11.6
- RS Toolkit d8a3d6f3
- Mono 4.8 (`mono-4.8.0-branch/8f6d0f6` - current `brew cask install mono` version)

**Comment by kfeuerherm** [comment]
Right, I'll get you more details as soon as I can, with some luck Monday afternoon.

Bandwidth isn't an issue, so I'm more than happy to help. Give me the link and we'll go from there.

Just FYI, computer science was my major back in the day and I worked for some years as an analyst programmer. That was all pre-internet etc., though... so this would be a good excuse to update myself a little....

**Comment by kfeuerherm** [comment]
Ok, here we go. Did a screencast for you. As I mentioned there in passing, I did succeed in repacking an ID earlier today, but in the video it did not work...

http://kfeuerherm.ca/RS/RSToolKit.mp4

**Comment by L0FKA** [comment]
Ok, I see you've got xcode and bunch of stuff

about crush in the end, ubi did some patches lately(month ago or so to adress this issue, have you updated to latest version? if it bothers you you could hit ubi support but let's talk about toolkit's stuff)

I see you tried with mac version of the cdlc workaround would be using beta version since release version is bugged with 4 byte left to read error(which is platform detection failure) which is fixed in beta version already plus you could set appid while you doing conversion for cdlc file so no extra steps after you converted to mac now.

Would recomend to use mono 4.0.4 from archive, since some sierra user report it's working fine for them (even tho monodevelop for mac needs mono 4.6.1 minimum) but that's in case you fail with beta version (I've got reports that 4.6.1 is fine too with Sierra\El Cap)

I'm doing also wine\wineskin build for mac with 100% featchure list, for those who author cdlc under mac, I'd like to have it done with at least 3-5 ppl

and that performance is oddly slow on i7 mac, should convert in like 5-10 seconds for 5-9 mb files.

also here's topic about mac from our friend Wepeel:
http://customsforge.com/topic/33889-how-to-add-custom-songs-on-mac/

**Comment by kfeuerherm** [comment]
1) Crash as the end: no, not bothered. I just mentioned it :) It doesn't always happen anyway, I'm shutting down so big deal.
2) Yes, 4 byte error, that is what I was talking about at the beginning. Usually I do not try beta software but in this case (if I'm going to help with testing) that's ok, I will try that.
3) Mono: if I have problems, I'll check the older version. Justin used 4.8 (above).
I'll get back to you when I've had the chance to try these things out.

I teach university, *one week to go*, then marking. So right now, not a lot of time. But, after that, I can learn about git and EOF and all that stuff so I can be more productive then.

**Comment by cozy1** [comment]
@L0FKA  Amy Winehouse file mentioned above: https://www.dropbox.com/s/a8zcmvpt7gxh91j/Amy-Winehouse_Rehab_v1_DD_p.psarc is produced with very old and unreliable version of toolkit 2.5 which is prone to 4-byte error.  I would not waste my time much with this one.

**Comment by L0FKA** [comment]
@cozy1 have CFSM came to macOS Sierra? or mac at all, I think we should put new minor release then, so peaple who trust stable version more than dev builds should benefit from new features, I'm going to add replaygain which should be almost 95% accurate on getting perfect song volume value, etc..etc

@kfeuerherm 
Got it, git stuff is nothing to learn with "smart git" or "github4windows" or the one from altsian "source tree" app, but if you go with console version of it i think it would be a bit harder, but teachers in IT area  should quickly get the idea of new tecnology (oh my, it's almost like 10 years already here). keep up.

**Comment by JustinAiken** [comment]
> @cozy1 have CFSM came to macOS Sierra? or mac at all

I've never been able to get CFSM working on Mac at all - not with Wine, not with Mono, not at all :/

**Comment by cozy1** [comment]
CFSM offers no support for Mac.  CFSM can repair PC psarc very well which can then be converted to Mac with toolkit.  @L0FKA I can do new release version of toolkit whenever you want.  Just let me know when you think you have Mac issues tidied up.

**Comment by L0FKA** [comment]
@cozy1 sure, I'm planning it on 1st april :D

**Comment by L0FKA** [comment]
@kfeuerherm I mysel don't use cuneiforms in general but I like Amon Amarth and guys use runes style in their fonts for album cover art.... Yes I like those papers about IT history in general about BellLabs and first compy with no GUI and printable output, my first PC was IBM PC i486 cpu from intel and 1 gb hard drive, used mostly for gaming in CIV and some racing. 

About issue I'm sure it's solved by cozy1 in beta version, not counting that cdlc is built with old toolkit it should work, tested on converted version of the file.
Also if you have any suggestions about UX (User expirience) / UI (user interface) I'm gladly add those in my TODO list.

**Comment by kfeuerherm** [comment]
@LOFKA ok…

@anyone I seem (??) to have got the old version of Mono off my system and am happy to try other versions. I have on my backup drive packages for 4.2.1.102, 4.4.0.142, 4.6.1.5 and 4.8.0.520. I recall it was a bit of an effort to instal it in the first place and I’d like it to be available in command line also. Have homebrew… but all the info I can find on-line is outdated either with regards to homebrew or with regards to OS X…. If you could help me figure out how to instal specific versions (potentially also ones I don’t have) so it will work in command line, I would be grateful…

**Comment by JustinAiken** [comment]
`brew cask install --force mono-mdk` will give you 4.8, which works for me on El Capitan.

**Comment by kfeuerherm** [comment]
Alright, I will try that. But I thought the idea was to do broad range testing. I understand that if I have multiple versions installed, I can use brew switch to alternate….?

**Comment by kfeuerherm** [comment]
I have since verified that the Repack ID works fine with a Mac .psarc under the Beta version. However, further experimenting with opening folders shows that this is a very erratic operation. If need be I can create another video tomorrow to showcase this. If others could simply try to open various folders on the desktop and elsewhere and get a sense of how it works that would be good.

**Comment by kfeuerherm** [comment]
Ok, installed mono 4.8 as suggested. Downloaded beta for Mac:
From the about: 
Doesn’t work properly from downloads (e.g. trying to set the project folder causes the app to bomb), likely that’s normal. Moved to Applications.

Configured the fields I understand.

 I can understand if you want to maintain a comparable interface. But suggestion: if some of this stuff doesn’t apply to Mac, gray out the fields or make them inaccessible?
Also, is there a help/doc file somewhere that explains what all the options are? It’s not necessarily altogether straightforward unless all the codes and buzzwords are known up-front.

Downloaded a CDLC from avdocat, placed it in the project folder. Attempted to navigate to that folder, but this did not work. See below:


This is the folder which opened instead:


So something is not right. I will move the file to there just so I can continue testing but maybe someone else can try something similar?

**Comment by L0FKA** [comment]
No screens attached for me (nor videos too)
Suggestion about graying out useless options is good, noted.
About wiki pages, we should write some basic instructions, but yeah, for me it's all obvious, and people usually refer to a certain guides so there explained what you need to do, also on creator form should be tips popup on each field(it's may be missing on mac, but on windows It's there)

As for the missing screens, I'd like to see them. I know mono has odd OpenFileWindow design and behaviour, I've got errors with it too SaveFileWindow is better but not much.
I constantly fail to install NET framework on wine bottle so no toolkit and wwise for now. maybe I should try crossover, hmm.

**Comment by kfeuerherm** [comment]
@LOFKA Missing screens.. Not sure what you mean. You mean from my message? I didn’t do the video yet showing the erratic folder behaviour. I can do that in an hour or so. I can post those on my site (maybe should do that anyway in future).

Manual: I do typesetting… I am happy to put together a PDF manual for this, little by little, if you are interested… as I figure out how it works :) Let me know if that would interest you.

**Comment by kfeuerherm** [comment]
@LOFKA Ok, I reposted what I said yesterday here: http://kfeuerherm.ca/blog/rs-toolkit-1703029/ <http://kfeuerherm.ca/blog/rs-toolkit-1703029/>

(While I was at it, I clarified the language a bit, and at the end I added another item about the icon which appears in the tray. As noted, I did not produce a video because I could not replicate the problem of directories/folders today!)

**Comment by L0FKA** [comment]
About copywrite thing I guess it should be just a field which would update itse'f each build, hmm.
I'm not familiar with Application folder behaviour, but google says it's because Protection from running notsigned apps by apple's ID hash, whaewer. you may find way to fix that without disabling that protection? try this just to make sure it's out case (http://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/)

Toolkit use latest opened folder across the app, I've got bug with missing directory separator char for browser dialogs so it going off the folder you need, but that's for Packer/Unpacker tab.
Icon, I saw it before in my VM, it should be fixed icon from icns repo, but it goes back and foth somehow, advice (right click the bundle and click Get Info, the icon shows up in the 'preview' section.)
stackowerflow suggests that's something about untrusted apps but may be also missing fields inside app bundle config.

About PDF with guideness on toolkit's features, I guess It would be something we might use as reference, since I'm not sure I'll be able to write docunentation thing for the app. I know Berneer (@ CF) did a great tutorial on EOF's  tech notes feature so it became as simple as doing regualr charting for the song.

**Comment by kfeuerherm** [comment]
Oh, I never even thought about the copyright thing….

I’m not worried about running the app outside Applications folder. I was just making a comment so you would know about it :)

Ok about icon. It is also not a big deal… just might confuse some users….

Documentation… Right, I can work on this as I go. I will looke for the tech notes on EOF sometime.

For other suggestions and comments, do you want to keep using this thread? We’re not really talking about the original problem any more….

**Comment by JustinAiken** [comment]
> I’m not worried about running the app outside Applications folder. I was just making a comment so you would know about it :)

... although it would be great if it read the `RocksmithToolkitLib.Config.xml` from `~/Library/Application Support/RocksmithCustomSongToolkit` instead of in-app-dir 😉

**Comment by kfeuerherm** [comment]
Also, is there any way for the app to determine the OS directly, as some software does, rather than query the user via configuration tab? This could then in turn determine various other things (incl. the proposed graying out of inappropriate options) and would obviate certain user input errors…

**Comment by L0FKA** [comment]
Not related now. Use wined version of the toolkit.
