### ISSUE TITLE
dlcconverter.exe not being included anymore

### ISSUE THREAD

**Issue by JustinAiken** [rscustom/rocksmith-custom-song-toolkit#284]
- All builds prior to 008d4679289e18212833f830dc3bcd0d05073bfc had `dlcconverter.exe`
- All builds starting there and forward lack it

**Comment by cozy1** [comment]
Thanks.  Looks like all the CLI's are missing.  I will look into it.

**Comment by JustinAiken** [comment]
Also, if I copy `dlcconverter.exe` from the last working release into the current, running it fails:

```
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'NDesk.Options, Version=0.2.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'NDesk.Options, Version=0.2.1.0, Culture=neutral, PublicKeyToken=null'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'NDesk.Options, Version=0.2.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'NDesk.Options, Version=0.2.1.0, Culture=neutral, PublicKeyToken=null'
```

Whereas running the `dlcconverter.exe` directly from the last working release worked fine... so maybe some fonts or other things missing from the package too

**Comment by cozy1** [comment]
Not sure about that.  Sounds like Wine issue.  Could also be issue that old CLI does not play well with new toolkit lib.  I will re-add CLIs and you can test then.

**Comment by cozy1** [comment]
@L0FKA How are CLI executables updated in the RocksmithCustomSongToolkit.app/Contents/Resources folder?  You doing it manually?  I will restore CLI build for PC version but this looks like something that is effecting Mac version too.

**Comment by L0FKA** [comment]
@cozy1 you've removed "unused" dependencies from gui project file so you've got no cli tools anymore, look in this commit (a0013c364ea5c791aa707a68ea4ed28b24c08d3b)

**Comment by cozy1** [comment]
@JustinAiken Plz try now.  CLI's should all be restored.  Also added a new batch file for doing conversions.  Simple drag/drop CDLC to batch to convert PC to Mac.  CLI name has changed to cdlcconverter.exe  Let me know if it works for you.

**Comment by cozy1** [comment]
@L0FKA It is fixed now but what about the comment about Mac build folder?  How are you updating this?

**Comment by JustinAiken** [comment]
```bash
$ wine \
  /Applications/RocksmithCustomSongToolkit.app/Contents/Resources/cdlcconverter.exe \
  --sourceplatform=Pc
  --targetplatform=Mac
  --appid=248750
  --input=/Users/jaiken/Desktop/JerryC_Canon-Rock_v2_0_DD_p.psarc

Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Found '1' DLCs in '/Users/jaiken/Desktop/JerryC_Canon-Rock_v2_0_DD_p.psarc'
-----------------------------------------------------------------
Processing DLC [1 / 1] 'JerryC_Canon-Rock_v2_0_DD_p.psarc' ...

[....]
[....]
[....]
[....]
[....]
[....]

DLC JerryC_Canon-Rock_v2_0_DD_p.psarc converted from 'Pc' to 'Mac'.
-----------------------------------------------------------------
'1' DLCs successful processed.
```

👍

**Comment by L0FKA** [comment]
@cozy1 mac app bundle didn't produced with regular mac build now, it's done using appveyour script (you can see it's in build scripts some of the files there.. maybe we should build mac version on mac into app bundle?

**Comment by cozy1** [comment]
@L0FKA I was just asking if most current libs and CLI were being included in Mac build like PC build?  I didn't see where this was happening.  If Mac build is not using fresh toolkitlib lib it could explain a lot of the problem.

"you've removed "unused" dependencies from gui project file so you've got no cli tools anymore, look in this commit (a0013c3)"  This actually speeds up the development build process because in IDE debug mode the CLI projects are not being unnecessarily built.  I used different method to pull CLIs into appveyor build which seems to be working nicely now.  Also removed unnecessary files from toolkit project folder.

**Comment by L0FKA** [comment]
@cozy1 just pointed out this is pulled off and and it didn;t put back, so that's it.
mac release generally reorganized win build, since appveyour have no mono compiler, right?
ok I think it's broken under mac again, because of build event you added w\o platform specific check :)

**Comment by cozy1** [comment]
You pulling my leg ... our buddy Justin says 👍
