### ISSUE TITLE
AppVeyor Errors

### ISSUE THREAD

**Issue by cozy1** [rscustom/rocksmith-custom-song-toolkit#285]
@ray I added a new CLI tool to toolkit project and now AppVeyor is throwing error:

SignTool Error: File not found: C:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\bin\Release\RocksmithToolkitGUI.exe
SignTool Error: File not found: C:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\bin\Release\RocksmithToolkitUpdater.exe
SignTool Error: File not found: C:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\bin\Release\RocksmithToolkitLib.dll

Any ideas?

**Comment by ray** [comment]
Take a look at the actual build log. It's only building single project:
```[00:00:11] msbuild "C:\projects\rocksmith-custom-song-toolkit\RocksmithCustomSongCreator.sln" /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
[00:00:11] Microsoft (R) Build Engine version 14.0.25420.1
[00:00:11] Copyright (C) Microsoft Corporation. All rights reserved.
[00:00:11] 
[00:00:15]   artistfolders -> C:\projects\rocksmith-custom-song-toolkit\RocksmithToolkitCLI\artistfolders\bin\Release\artistfolders.exe```

Removing AnyCPU under Build > Configuration manager will fix it.

**Comment by cozy1** [comment]
@ray  Wow!  Thank you.
