### ISSUE TITLE
Q: documentation on the CLI tools?

### ISSUE THREAD

**Issue by Silox** [rscustom/rocksmith-custom-song-toolkit#286]
In the root folder of the repo, there is a folder RocksmithToolkitCLI hinting at a CLI interface. Is this the case, and if so, is there any documentation on how to use them? I'd like to convert songs on OSX with the command line to be able to process multiple songs in batch.

**Comment by JustinAiken** [comment]
> I'd like to convert songs on OSX 

```bash
wine \
  /Applications/RocksmithCustomSongToolkit.app/Contents/Resources/cdlcconverter.exe \
  --sourceplatform=Pc \
  --targetplatform=Mac \
  --appid=248750 \
  --input=some_p.psarc # You can also point to a folder instead of an individual psarc, and it'll do the lot
```

**Comment by cozy1** [comment]
@Silox The CLI are primarily intended for PC users.  Each CLI has a help menu that is accessed like most other CLI, e.g. cdlcconverter.exe /? 
Follow @JustinAiken  instructions for using the CLI with OSX.

**Comment by Silox** [comment]
That'll work, thank you!
