### ISSUE TITLE
Generating DD changes volume from 0 to -12

### ISSUE THREAD

**Issue by iminashi** [rscustom/rocksmith-custom-song-toolkit#290]
If you generate DD on a psarc file where the song volume is set as 0.0, it will be changed to -12.0.

**Comment by L0FKA** [comment]
Truly a bug for me but it's made intended so it will have default value, I'll write function to get individual song and preview volume values from bnk, adding to todo list, thanks

**Comment by cozy1** [comment]
Have we determined if this is bug with DDC or toolkit?  Toolkit can be used to apply a workaround if needed.

**Comment by cozy1** [comment]
Fixed https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/8e59dbd5f989612e0c464104c794d44d66bfc36e

**Comment by L0FKA** [comment]
@cozy, I'm finishing with bnk format for RS2014, gotta draw quic read function since it's almost fixed in bnk, gimme 2 days for this :)
