### ISSUE TITLE
Spaces should be allowed in lyrics

### ISSUE THREAD

**Issue by iminashi** [rscustom/rocksmith-custom-song-toolkit#291]
Spaces are being filtered from lyrics.

e.g.
`  <vocal time="11.714" note="254" length="0.322" lyric="Test 1 2 3+"/>`
becomes
`  <vocal time="11.714" note="254" length="0.322" lyric="Test123+" />`

Normally, when doing lyrics by syllables, this doesn't matter, but in some cases one might want to have spaces in a lyric.

**Comment by cozy1** [comment]
@iminashi Need to add space to special characters.  https://github.com/rscustom/rocksmith-custom-song-toolkit/blob/124971959a6f157707b6f4d1ab02fc3d61fafade/RocksmithToolkitLib/Extensions/StringExtensions.cs#L197  Will fix in next release.

**Comment by cozy1** [comment]
Fixed https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/8e59dbd5f989612e0c464104c794d44d66bfc36e
