### ISSUE TITLE
AppVeyor Issue

### ISSUE THREAD

**Issue by cozy1** [rscustom/rocksmith-custom-song-toolkit#294]
@ray I added a new project to the repo and now I have an AppVeyor error.

How do I fix this error?  => 'Specify which project or solution file to use because the folder contains more than one project or solution file.'

Thanks
https://ci.appveyor.com/project/rscustom/rocksmith-custom-song-toolkit/branch/master

**Comment by ray** [comment]
Delete the RocksmithDevBuilder.sln. There should only be one solution file unless you explicitly tell it which one to use.

**Comment by cozy1** [comment]
Thank you.  I would like to figure out how to tell AppVeyor which to use explicitly for the future.

**Comment by ray** [comment]
From the docs (https://www.appveyor.com/docs/appveyor-yml/), this would probably work:
```
build:
  project: RocksmithCustomSongCreator.sln
```

**Comment by cozy1** [comment]
Thanks, Ray.  We should talk more ... you are a good teacher.
