### ISSUE TITLE
Add option to stop loaded package overwriting AppId

### ISSUE THREAD

**Issue by tobybrad** [rscustom/rocksmith-custom-song-toolkit#298]
I use a different appId for CDLC (I know, I know).

Whenever I load a new package the appId I set is reset to the one in the package file. This can make importing a bunch of files a pretty tedious business.

Would be great to have a 'Lock Id' check next to appId box to prevent this happening. When checked the appId remains as I set it. When unchecked, existing behaviour.

Great work on the GUI though. Very useful tool.

**Comment by cozy1** [comment]
Request seems reasonable and since you did the work.  Sure, added it here: https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/5de809b92af6c9da9432a5282d687630f4278240

**Comment by cozy1** [comment]
Going to move this to the General Config page so that LockAppId is saved in the settings though.

**Comment by cozy1** [comment]
Done https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/5451e04aa4549fbc38e81a108ea2138f7b660825
