### ISSUE TITLE
Audio Quality is always 4 in the template

### ISSUE THREAD

**Issue by Chlipouni** [rscustom/rocksmith-custom-song-toolkit#302]
When I use the RSToolkit to create a new CDLC, I always set the Audio Quality Level to 8.
Once the template is saved, the Audio Quality is setted with its default value of 4.
If the RSToolkit offers the possibility to use a higher level of encoding it should restitute the value chosen by the user.

**Comment by cozy1** [comment]
TODO: Add audio quality to General Config settings.

**Comment by cozy1** [comment]
Added audio quality factor configuration to General Configuration settings [here](https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/1f3374c7b4cb15eacbb2d8370642c1a8632bb078)
