### ISSUE TITLE
Two problems with Japanese artist/title

### ISSUE THREAD

**Issue by iminashi** [rscustom/rocksmith-custom-song-toolkit#304]
1. The manifest attribute name should be  "JapaneseArtistName" instead of "JapaneseArtist".

2. Empty strings shouldn't be serialized. Otherwise you'll get this:

![20180225150617_1](https://user-images.githubusercontent.com/23147580/36726291-e30d14ac-1bc1-11e8-9732-56717e796381.jpg)

**Comment by L0FKA** [comment]
Like for the Fantasy Seph's
about "Empty strings shouldn't be serialized. Otherwise you'll get this" you mean like whole thing or just Japanese one? right?

**Comment by iminashi** [comment]
When playing the game in Japanese, the game won't display a title since the Japanese title for the song is set as "". I noticed a couple of such titleless customs among the ones I downloaded recently. I didn't have a working computer for quite a while so I wasn't able to test sooner.

**Comment by L0FKA** [comment]
Oh, so I'll kill that empty string it was intended to mute like that actually.

**Comment by AgonasiGen** [comment]
Song title was displayed in Japanese, but artist name is displayed in English. Is this a bug?

**Comment by iminashi** [comment]
Yes, the attribute name for Japanese artist is wrong. It will work once it's renamed to "JapaneseArtistName".

**Comment by AgonasiGen** [comment]
I see. understood. wait for it to be fixed.thank you so much.

**Comment by L0FKA** [comment]
Well simple rename should help anyway I don't allow toolkit to write empty japanese-fields in json fines, I'll commit changes within uhd support so feel free to report odds in "refreshed" interface :)
