### ISSUE TITLE
Add repack folder button to Repacker/Unpacker interface

### ISSUE THREAD

**Issue by ozars** [rscustom/rocksmith-custom-song-toolkit#308]
Hello!

I was procrastinating to repack some songs since they were in bunch of different folders... and I decided to add a repack folder button to GUI in Packer/Unpacker. Thought you might be interested in. Would you want me to submit a PR?

Thanks for this wonderful tool!

**Comment by L0FKA** [comment]
@ozars seems valid function at first glance let me test it :)

**Comment by ozars** [comment]
@L0FKA Well, I just copied and modified existing function in fact. So, it should have same behavior with that of Repack AppId button.

**Comment by L0FKA** [comment]
@ozars I think it's more of like separate tab or group function since it targets multiple files and could be used in CFSM more than on packer tab. still valid thing tho.

btw do you have knowledge how to cover legacy code with tests or write code through TDD? just curious

**Comment by ozars** [comment]
> I think it's more of like separate tab or group function since it targets multiple files and could be used in CFSM more than on packer tab. still valid thing tho.

Technically, Repack AppId button already accepts multiple files from same folder, but I got your point. Anyway, I'm not submitting PR then?

> btw do you have knowledge how to cover legacy code with tests or write code through TDD? just curious

I have a general idea but not much experience tbh. I wrote some code with unit tests but they weren't in C#.

**Comment by L0FKA** [comment]
@ozars  I've got my uhd support project done 75% so you should pr that sooner than I push my commits :+1: I'm w8ting for you

**Comment by ozars** [comment]
@L0FKA OK. Submitted it. Thanks for feedback. Closing the issue.
