### ISSUE TITLE
Crash converting PC to Mac.

### ISSUE THREAD

**Issue by Junglejon** [rscustom/rocksmith-custom-song-toolkit#316]
Would love to contribute if I could be helpful, just need to get ramped up.

Found a crash today On Mac
1) Goto convert tab
2) Choose to convert from PC to Mac
3) Load an Mac file

Results
Crash.

**Comment by L0FKA** [comment]
Have you tried our mac port of the toolkit? if you're using it report in that topic!
https://customsforge.com/index.php/topic/39922-latest-rstoolkitwine-releases-10-27-2017/
