### ISSUE TITLE
GameVersion_MouseUp being triggered unintentionally

### ISSUE THREAD

**Issue by iminashi** [rscustom/rocksmith-custom-song-toolkit#321]
1. Position the Load Template open file dialog so that one of the radio buttons will be below the filename/mouse.
2. Double click the file.
3. GameVersion_MouseUp is called and the form is reset.

**Comment by cozy1** [comment]
Wow how did you find that bug?  After research this is apparently a [know issue](https://social.msdn.microsoft.com/Forums/vstudio/en-US/f4c81f91-1f19-4896-92b7-9fa5ed60db8a/stop-mouse-from-firing-on-double-click-in-opendialog?forum=csharpgeneral) with VS.

Switched MouseUp to MouseDown to fix bug https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/5f1a2c9b6a88d1be47099c9debcf5a1bddebcf1f

**Comment by iminashi** [comment]
It actually happened the first time I tried opening a template.

**Comment by cozy1** [comment]
@iminashi  Guess you got lucky or not.  It took me a few tries to reproduce the bug.  Thanks
