### ISSUE TITLE
Can't import package with latest beta 

### ISSUE THREAD

**Issue by Firekorn** [rscustom/rocksmith-custom-song-toolkit#322]
https://imgur.com/otkRZLO
Here is the log file : 
[_RSToolkit_2018-08-04.log](https://github.com/rscustom/rocksmith-custom-song-toolkit/files/2259502/_RSToolkit_2018-08-04.log)

This happens on any attempt to import a package to the toolkit on version  v2.8.4.1-5f1a2c9b Beta

**Comment by L0FKA** [comment]
Wasn't around in town, so issue [with this function](https://github.com/rscustom/rocksmith-custom-song-toolkit/blob/174234a9e66ed54bd68af37357a94731a4a72a18/RocksmithToolkitLib/DLCPackage/DLCPackageData.cs#L842) basically it can't move files to different drives

**Comment by cozy1** [comment]
@Firekorn Added IOExtensions for cross server/drive compatibility.  Please see if this fixes the issue.  https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/1a24bf3acd5375abcd5c8d7817974bceb0c795d4

**Comment by Firekorn** [comment]
Working perfectly fine, thanks
