### ISSUE TITLE
'File not found' error - CDLC Package Creator

### ISSUE THREAD

**Issue by angk500** [rscustom/rocksmith-custom-song-toolkit#323]
When generating a new package I receive an error message. 'Could not find file'
![image](https://user-images.githubusercontent.com/42495582/44300238-1d34db00-a304-11e8-859c-4e9b5268dd41.png)

tmp folder is empty.

**Comment by angk500** [comment]
Issue is caused by album art. Using the 'Default' album cover makes it work. Album cover is a .bmp file. Trying with different file format next.

**Comment by L0FKA** [comment]
Can you open that bmp file in paint for example? could it be damaged? nvdxt should work fine with bmp format and error said something about .dds file not found so it could be something else and it really could be nvdxt issue with bmp files then. We need to investigate this.

**Comment by angk500** [comment]
I have tried to open this file with various programs including photoshop. It does open without any problems. It was converted with an online converter, so I was also thinking it could be corrupt.
For your curiosity, this is the image I am using:
https://www.dropbox.com/s/kyz5xlx7eyoudgn/a2697307231_16.bmp?dl=0

To get some troubleshooting work off your hands: I have converted another file, this time not resized. Same issue. I have tried another image, resized, same issue. I have tried to resize it with photoshop and convert it into .gif and into .png. These work perfectly fine. Seems like it is a file format problem.

**Comment by cozy1** [comment]
Have you tried using a 512x512 jpg of that cover?  bmp's can be iffy.

**Comment by cozy1** [comment]
The 24-bit bmp image you are feeding the toolkit is incompatible with with the converter.  Plz try a 32-bit image and let us know.

**Comment by cozy1** [comment]
@angk500 Fixed bmp to dds image converter here: https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/a81c9a7a2ce9372da06d08a930a6c162b057f57e
Only 32-bit bmp images are supported by the converter.  Plz try it and give feedback.

**Comment by L0FKA** [comment]
well I'd rather drop bmp support or do it in hackish way with reading bmp using gdi and saving to png or any other format before feeding it to nvdxt

**Comment by L0FKA** [comment]
In other words - please do it yourself then? I'll try to this weekend no matter what.

**Comment by cozy1** [comment]
I'm ok with it as-is, bmp conversion works again.  So if you want something different ... go for it.

**Comment by iminashi** [comment]
@cozy1 
Changing the nvdxt arguments broke something else and now there are ugly transparent pixels in my cover picture that weren't there before:

![Screenshot](https://i.imgur.com/0ZwfROL.jpg)

**Comment by L0FKA** [comment]
@iminashi Alpha channel is missing now so it's obvious that any ex-transparent pixels become solid color and has overall worse quality I'd rather change it to dxt5 since size ain't that matter here and quality may improve a bit :)

**Comment by cozy1** [comment]
Better option is to deprecate support for bmp files and restore the original dxt1a format.  @L0FKA can play with GDI support when he has time.

**Comment by cozy1** [comment]
Done https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/afa7e01b43c69a3373a596d1bd54153884572cba

**Comment by cozy1** [comment]
@iminashi Let us know if dxt1a artwork is working again.

**Comment by iminashi** [comment]
It is indeed working again.
