### ISSUE TITLE
No platform selected on CDLC creator tab

### ISSUE THREAD

**Issue by Firekorn** [rscustom/rocksmith-custom-song-toolkit#329]
By default, no platform is selected by default with the latest beta.

**Comment by cozy1** [comment]
Thanks.  Fixed [here](https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/769dc502627bf1d7b359051317cacda439321d64).

**Comment by cozy1** [comment]
Perma fixed [here](https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/e38678baa849809c401be7d37c9cf7cccc4d679a).
