### ISSUE TITLE
Revise rscustom.net link to Release Notes

### ISSUE THREAD

**Issue by cozy1** [rscustom/rocksmith-custom-song-toolkit#334]
@ray On the www.rscustom.net  'Welcome to the Rocksmith Custom Song Project!' page ... 

Please assign the 'Release Notes' blue link label that is next to the 'Windows' and 'Mac' green download buttons to:
https://raw.githubusercontent.com/rscustom/rocksmith-custom-song-toolkit/xxxxxxxx/RocksmithTookitGUI/ReleaseNotes.txt    where 'xxxxxxxx' is a dynamic abbreviation of the latest git subversion.   This would allow users to read the latest toolkit ReleaseNotes.txt file directly in their web browser by clicking the link.  

If it's not possible to create such a dynamic link then please remove the 'Release Notes' blue link label that is next to the green download buttons.  We can manually update the other 'Release Notes' link that is in the latest news section as significant commits are release.   Thanks

**Comment by cozy1** [comment]
Discord User: Ffio comments on the issue:
In reference to: https://github.com/rscustom/rocksmith-custom-song-toolkit/issues/334 ... Because if you it was automated then I could see the use of a variable for the revision number already in use. Though if it was manually added (per build/ commit) I wouldn't know if it was a commit or not. If it isn't automated / isn't a variable could you set the release notes to do something like "https://raw.githubusercontent.com/rscustom/rocksmith-custom-song-toolkit/" . $recentCommit . "/RocksmithTookitGUI/ReleaseNotes.txt" where $recentCommit would be $recentCommit = substr($latestBuild, -9, 8) and $latestBuild would be this string "Latest build - X.X.X.X (rev XXXXXXXX)" (with filled in data). I think this would work because substr($latestBuild, -9, 8) will get the last 9 letters/symbols/numbers and count for 8 letters (the revision code minus the parenthesis)

**Comment by ray** [comment]
Done

**Comment by cozy1** [comment]
Thanks
