### ISSUE TITLE
Startup error for loadFromRemoteSources 

### ISSUE THREAD

**Issue by Andrea2202** [rscustom/rocksmith-custom-song-toolkit#335]
When trying to start RocksmithToolkit GUI, I run into the following issue:

"An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information."

The solution is to add
```
<configuration>
    <runtime>
       <loadFromRemoteSources enabled="true"/>
   </runtime>
</configuration>
```

into app.config

Can you add it to fix the bug?

Thanks

**Comment by Andrea2202** [comment]
@cozy1 I tried now with AV disabled but the same error appears. I think the error is due to the new security policies of the .NET framework version inserted in the new windows 10 october update.

**Comment by DarwinLebowski** [comment]
so I'm kinda new here but i just whitelisted it and it still won't open. 

but in the meantime I'm willing to change the app.config file, if anyone can explain how/point me in the right direction it would be greatly appreciated.

**Comment by Andrea2202** [comment]
@DarwinLebowski Unfortunately, the file is internal to the repo. You must to modify the sources and recompile the whole application using Visual Studio. Currently the easiest way is to wait for the new release, hoping it will be done soon.

**Comment by cozy1** [comment]
@Andrea2202 @DarwinLebowski [Latest toolkit build](https://www.rscustom.net/) has the suggested app.config file.  Please test and confirm the fix.  Are you on Windows 10?  Are you receiving MS updates?

**Comment by cozy1** [comment]
@Andrea2202 @DarwinLebowski Critical ThirdPartyApps were missing from the build. Let me know if latest build is working again for you.

**Comment by Andrea2202** [comment]
@cozy1 Thanks for your update! Now works perfectly! Thanks a lot!
