### ISSUE TITLE
RocksmithToolkitGUI startup crash System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by Ariloum** [rscustom/rocksmith-custom-song-toolkit#336]
Can't launch RocksmithToolkitGUI on Windows 10 v1803 build 17134.472

There is a chain of errors in windows event viewer with FileNotFoundException.
Application: RocksmithToolkitGUI.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(System.String)
   at RocksmithToolkitGUI.Program.Main(System.String[])

**Comment by cozy1** [comment]
@Ariloum Please download and reinstall toolkit [latest toolkit build](https://www.rscustom.net/).  Let me know if this fixes your problem.

**Comment by Ariloum** [comment]
I tried last build and error still persists.

Faulting application name: RocksmithToolkitGUI.exe, version: 2.9.2.0, time stamp: 0x5c5071b4
Faulting module name: KERNELBASE.dll, version: 10.0.17134.441, time stamp: 0x3da51fd0
Exception code: 0xe0434352
Fault offset: 0x00111812
Faulting process id: 0x5250
Faulting application start time: 0x01d4b7ed00f773de
Faulting application path: D:\games\rstoolkit-2.9.2.0-71de56d6-win\RocksmithToolkit\RocksmithToolkitGUI.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 6ee049d4-5e81-4525-af96-3b8322e821a5
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Fedro64** [comment]
For my part, the last two updates do not open even more (PC under W7)

**Comment by cozy1** [comment]
Thanks.  Checking into now.

**Comment by cozy1** [comment]
@Ariloum  @Fedro64 Critical ThirdPartyApps were missing from the build.  Let me know if it is working again for you.

**Comment by Fedro64** [comment]
Thank you @cosy1
This seems to work even though I have not yet test the functions that I usually use.

**Comment by Ariloum** [comment]
Yep the bug is gone, thank you.
