### ISSUE TITLE
Invalid Readme alias on Mac Wine port

### ISSUE THREAD

**Issue by kfeuerherm** [rscustom/rocksmith-custom-song-toolkit#338]
Just out of curiosity downloaded the Mac Wine Port .dmg today as my system (10.14.3 (18D109)) warns me that the current toolkit won't run in future upgrades to the OS... and we've discussed the whole mono dependency thing in the past....

The site instructions read " follow the included ReadMe instructions once you have mounted the image"... unfortunately the alias appears to point to "/Users/cozy1/Desktop/Rocksmith Tools 1.5.1.3/Rocksmith Tools Launcher.app/Contents/Resources/drive_c/Program Files/Launcher/ReadMe.txt" which is not terribly helpful!!! (and there's no ReadMe.txt file on the .dmg ...)

**Comment by cozy1** [comment]
Try the latest build.   Fixed the included ReadMe.txt file.

**Comment by kfeuerherm** [comment]
Ok, seems to work now. Thanks!
