### ISSUE TITLE
Index out of Range Converting PC to PS3

### ISSUE THREAD

**Issue by uspwue** [rscustom/rocksmith-custom-song-toolkit#339]
Hello,

I have converted 1124 RS dlc songs from PC to PS3 but I got an issue on only one song.

Here is the only logs I can cut/paste (the error exception report is in a window box I can cut out of). Also, the messages shows in french so I'm not quiet sure about the exact phrasing of the error: "Index out of Range" -> "L'index se trouve en dehors des limites du tableau".

The source psarc is there: EDITED:  Removed link to inappropriate material

_RSToolkit_2019-05-06.log
[_RSToolkit_2019-05-06.log](https://github.com/rscustom/rocksmith-custom-song-toolkit/files/3146896/_RSToolkit_2019-05-06.log)

**Comment by cozy1** [comment]
Content Violation
