### ISSUE TITLE
Packer / Unpacker Decode Audio Renaming or Wem File renaming v2.9.2.0

### ISSUE THREAD

**Issue by Hypasonik** [rscustom/rocksmith-custom-song-toolkit#341]
When unpacking the Audio that decodes to *.ogg doesn't rename it properly. It always use to stick with what the wem is, so either the *.wem is not renaming properly when unpacking like it use to, or that is intentional?

**Comment by cozy1** [comment]
@Hypasonik  It is intentional.  Fixed ogg files have user friendly names, e.g. song_peppapig_fixed.ogg.  The wem file names, e.g. 309467679.wem aren't very user friendly.  Either file will work with the toolkit.

**Comment by Hypasonik** [comment]
That is what I am saying, It used to be song_peppapig_fixed.ogg / song_peppapig.wem and now it is 309467679_fixed.ogg / 309467679.wem . So it is now un-user friendly

**Comment by cozy1** [comment]
Are you using latest build?  Need your workflow.

**Comment by Hypasonik** [comment]
Yes latest build 2.9.2.0

**Comment by cozy1** [comment]
Try a different CDLC.   Toolkit is not intended for use with ODLC.

**Comment by Hypasonik** [comment]
Tested with A few CDLC and it still does it :/ maybe I should try the standard 2.9.0.0 version.
