### ISSUE TITLE
Adding previews

### ISSUE THREAD

**Issue by cokolwiek235** [rscustom/rocksmith-custom-song-toolkit#344]
I am trying to add just the previews by editing (importing) the existing package in the CDLC Creator tab. Any way to do that without touching the song wem file?
Please help.
Thank you.

**Comment by L0FKA** [comment]
>Any way to do that without touching the song wem file?

What do you mean by 'without touching'? iirc toolkit would try to add preview autiomatically if none supplied based on first chorus section and full song file(it converts back to wem and gets preview encoded again)

**Comment by cokolwiek235** [comment]
Looks my custom DLC doesn't have those sections marked. And what I mean is if its possible to add just a preview without re-encoding the song. I don't want the main song to loose quality by encoding it back and forth. Thank you.

**Comment by cozy1** [comment]
just add the existing wem and toolkit creator will generate preview audio for you
make sure no other audio files are in the cdlc project folder other than the main audio wem

**Comment by cokolwiek235** [comment]
Alright, thank you. I just hoped that maybe you guys would add an option for that, so we wouldn't have to generate wem files ourselves, cause it takes more time to make them manually then it would take Custom Song Toolkit to do it. But that's alright. Thanks again.

**Comment by cozy1** [comment]
plz DM me on CF or discord you dont have to generate wem
