### ISSUE TITLE
Converting RS2012 to 2014 files results in an error

### ISSUE THREAD

**Issue by antifarben** [rscustom/rocksmith-custom-song-toolkit#345]
This was via GUI for a single song:
<img width="309" alt="rstk_error" src="https://user-images.githubusercontent.com/193328/74345254-1d555000-4dae-11ea-953b-782fe5e1b14a.png">

And I also tried the batch functionality by dragging a folder to `convert2012.exe` but this didn't work either:
```
Initializing Rocksmith 2012 CDLC Converter CLI ...

Unpacking: SOMESONG.dat
Converting RS2012 CDLC to RS2014 CDLC ...
Conversion could not be completed: Ein Teil des Pfades "C:\Users\User\Desktop\foo\bar\SOMESONG" konnte nicht gefunden werden.
```

**PS:** The error messages of the CLI tool translates roughly to "Could not find a part of the path"

**Comment by cozy1** [comment]
the error indicates that you are not using the conversion feature as intended.  plz dm me at cf or discord if you would like further assistance.

**Comment by antifarben** [comment]
Which of the _two_ errors do you mean exactly?

In the second case I just dragged a folder with `dat` files to `convert2012.exe`. Which is exactly [what it says](https://github.com/rscustom/rocksmith-custom-song-toolkit/blob/6b07b79cacfa5088c830cd5b4abdfe6e4895c58d/RocksmithToolkitCLI/convert2012/Program.cs#L43):

> Drag/Drop folder with *.dat files onto the console executable icon.
