### ISSUE TITLE
Packer/Unpacker will wipe`rs1compatibilitydlc_p.psarc` on errors

### ISSUE THREAD

**Issue by antifarben** [rscustom/rocksmith-custom-song-toolkit#346]
I did a batch conversion with the App ID Updater:
It ran into an exeption on `rs1compatibilitydlc_p.psarc`:

<img width="306" alt="rstk_error" src="https://user-images.githubusercontent.com/193328/74346290-aae56f80-4daf-11ea-8722-5c76349a8db4.png">

and wiped the file completely empty.

**Comment by cozy1** [comment]
because you can not change the a AppId of compatibility/song packs

**Comment by antifarben** [comment]
@cozy1 it is totally fine for me that the toolkit can't change IDs  of compatibility or song packs.

But damaging files instead ignoring them is faulty behaviour in my opinion.
Would you really expect that a tool destroys files from your installation?
