### ISSUE TITLE
Unable to convert to PS3 

### ISSUE THREAD

**Issue by bobenoni** [rscustom/rocksmith-custom-song-toolkit#349]
Rocksmith toolkit throws an error trying to convert to ps3. 
"No JDK or JRE is installed...
 ved
RocksmithToolkitLib.DLCPackage..."

Se full error message here: https://ibb.co/P9BRLBW

Xbox works fine.

Trying to follow advice from issue #317, but I do not have any user path containing java.

The only PATH entry for users is:
"%USERPROFILE%\AppData\Local\Microsoft\WindowsApps"

Toolkit creator 2.9.2.1
Freshly installed jdk 14.0.1 x64

**Comment by L0FKA** [comment]
Please Remove jdk and install JRE from java web site https://www.java.com/en/download/

it may not pick up jdk and x64 bit so it you could try to install x32 bit java as well

ps:
nice ps5 design *wink wink*

**Comment by bobenoni** [comment]
That did the trick. Thanks! ;)
