### ISSUE TITLE
Upload project to Nuget

### ISSUE THREAD

**Issue by kortov** [rscustom/rocksmith-custom-song-toolkit#352]
Hi, there is a project https://github.com/foxx1337/RocksmithToTab , which doesn't build anymore due outdated RocksmithToolkitLib.dll . I can upload it there as binary ofc, but I would like to do it the right way and to add is as a nuget package.

May be you'll add this project to nuget? As a reference you can look here https://medium.com/@wajahataliabid/github-actions-automate-nuget-package-deployment-1533b11d2be1 
as there are some api keys in nuget and github, I can't do it by myself. And I can't upload my fork due missing license file #351

**Comment by cozy1** [comment]
Sorry I don't work with nuget packages.  That repo is using a very old
version of the RocksmithToolkitLib.dll anyway which does not include the
lib validation check so that repo should build/work just fine as is.
Please request the author RocksmithToTab to update the library if you are
still having issues.

**Comment by L0FKA** [comment]
License for all C# is mostly MIT license but there's 3rd parties as well, but we should put rstkLib in separate repo, but that require some refactoring and additional work that may broke toolkit itself for a period of time. Also You can use toolkit as gui for cdlc2tab. as for updates it's were non important to rs2tab library we should update it, the thing works great as is already :thinking: 

p.s. Hello Samara city :wave:

**Comment by kortov** [comment]
ok I got you, thanks, I'll close the issue
