### ISSUE TITLE
CLI utils bug to update on latest build

### ISSUE THREAD

**Issue by ciandial** [rscustom/rocksmith-custom-song-toolkit#360]
Recently started seeing this warning popup when running CLI utilities like packer.exe, sng2014.exe.
I updated to latest but it persists.

```
Time To Update ...

**WARNING ...**

This version of RocksmithToolkitLib.dll is no longer supported.
Please download and install the latest version of toolkit.
```

**Comment by L0FKA** [comment]
Sure it's a killswitch added to keep bothering people so they'll update their tools it's toolkit's lib doing and should be disabled in next patch, thanks for heads up!

**Comment by ciandial** [comment]
Oks, solved by getting into Visual Studio, following contribution tutorial and building meself lib with new timestamps in it.
