### ISSUE TITLE
Not Possible to Convert The RS1 packs from PC to PS3 (from .psarc to .edat)

### ISSUE THREAD

**Issue by Hidden-sigh** [rscustom/rocksmith-custom-song-toolkit#365]
When selecting the file and converting, the following error appears every time. 
Win 10. Java installed. All other songs convert normally except this pack. 

Not sure what is wrong or what settings should be set. Help would be appreciated.

![2021-03-04_11-25-46](https://user-images.githubusercontent.com/80025543/109956290-2a601c80-7cec-11eb-8580-575675e3ee2b.jpg)

**Comment by cozy1** [comment]
Compatibility packs can not be converted.

**Comment by Hidden-sigh** [comment]
Thanks for looking into it @cozy1 . But is there some kind of workaround to this. Or is this undoable in any way?
