### ISSUE TITLE
Warning of out of date lib when running cdlcconverter

### ISSUE THREAD

**Issue by psoup1965** [rscustom/rocksmith-custom-song-toolkit#366]
When running CLDC Converter the user is presented with a popup stating "This version of RocksmithToolkitLib.dll is no longer supported." falsely. 
There was a procedure that checked for a timer of age on the assembly date of the library of > 180 days.
This message can be false and needs to be reconsidered if the check is really necessary since the GUI has a check for updates and I would think that a CLI run the user should be presented with a message and not a processing stopping popup.

**Comment by L0FKA** [comment]
It's a bit of a hacky way of doing this, but since you've commited some time to "fix" the issue I'll merge this, but there's more code to commit for me, anyway, thanks!
