### ISSUE TITLE
Missing WWise

### ISSUE THREAD

**Issue by bobbobbin** [rscustom/rocksmith-custom-song-toolkit#374]
Hi, I'm trying to figure this out.
When i try to change song information, I receive an error message 
ApplicationThreadException:
Could not Find Audiokinetic Wwise installation.
I see there are zipped files for Wwise in the latest package - i've
 unzipped them, but, this seems to do nothing?
I apologize if there's an obvious answer to this,  so I'll just add the LOG file generated.
Thank you
[_RSToolkit_2022-05-29.log](https://github.com/rscustom/rocksmith-custom-song-toolkit/files/8794726/_RSToolkit_2022-05-29.log)

**Comment by L0FKA** [comment]
Hello, can you log in your Customs Forge account you may visit this link https://ignition4.customsforge.com/cfsm/wwise

Wwise site doesn't provide that old versions of wwise

**Comment by bobbobbin** [comment]
thank you- that seemed to resolve the issue, cheers!
