### ISSUE TITLE
Support Rocksmith+

### ISSUE THREAD

**Issue by AndnixSH** [rscustom/rocksmith-custom-song-toolkit#378]
Can you add support for Rocksmith+ that uses sdfdata format? I want to be able to extract files from sdfdata.

**Comment by L0FKA** [comment]
You can save rsxml from your workshop and also share it with other creators, there's no plans to implement cdlc since it's online only service. But you can try to write a parser. I've heard it should have similar file formats to rocksmith2014.

**Comment by AndnixSH** [comment]
I don't make songs. I meant, I want to extract game assets in general. There are no tools that support sdfdata
