### ISSUE TITLE
Preview delayed

### ISSUE THREAD

**Issue by TheChilliPL** [rscustom/rocksmith-custom-song-toolkit#379]
Hey, I'm new to Rocksmith and I tried adding a custom song and it seems to have gone pretty well, except that introducing leading silence in EOF seems to introduce ~10 seconds of silence before the preview begins playing as well, which is not perfect. Is there any way to make that not happen?

**Comment by L0FKA** [comment]
Hello, you can place chorus section in your song and toolkit can find it and create preview for you, might as well use _preview.wem from previous test psarc?

**Comment by TheChilliPL** [comment]
I had to manually change the delay in EOF, regenerate the preview, and remove the WEM files that The Toolkit generated from `preview.ogg`
