### ISSUE TITLE
Generate WEM files in toolkit

### ISSUE THREAD

**Issue by x0l** [rscustom/rocksmith-custom-song-toolkit#85]
WEM files can be generated from WwiseCLI.exe as follow:
1. Create a project as usual in wwise
2. open the soundbank manager (F7) and check the appropriate platform settings
3. create a new soundbank under default unit and add your audio asset(s) to it
4. run `WwiseCLI.exe testproj.wproj -GenerateSoundBanks`

Audio assets will be converted to .cache

See the wwise sdk doc [Going Further > Generating Banks from the Command Line] for more options (like clearing the cache or selecting the target platform)

**Comment by cozy1** [comment]
Added Wwise CLI Integration to CDLCPackageCreator.
